[package]
name = "sliqtly-bench"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fjall = "3.1.12"
heed = "0.22.1"
redb = "4.3.0"
rocksdb = { version = "0.25.0", default-features = false }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde_json = "1.0.151"
sliqtly-kernel = { version = "0.1.0", path = "../sliqtly-kernel" }
