#!/usr/bin/env node
// SPDX-License-Identifier: MIT
//
// The web build: src/EditorApp.rgr → JavaScript, and the page around it.
// No bundler: the compiled app is one CommonJS file, wrapped here as an ES
// module (web/gen/app.js); EVG's browser helpers are copied beside it,
// following their relative imports; the fonts and the stylesheet too.
//
//   node scripts/build-web.mjs            # into web/gen/
//
// Also writes build/EditorApp.cjs, the same module for Node (npm test).

import fs from "node:fs";
import path from "node:path";
import { ROOT, install, compile, evgDir } from "./ranger.mjs";

const WEB = path.join(ROOT, "web");
const GEN = path.join(WEB, "gen");
const BUILD = path.join(ROOT, "build");

export function buildJs() {
  install();
  fs.mkdirSync(BUILD, { recursive: true });
  const compiled = path.join(BUILD, "EditorApp.cjs");
  compile(["-es6", "-nodemodule", "src/EditorApp.rgr", `-d=${BUILD}`, "-o=EditorApp.cjs"], compiled);
  return compiled;
}

export function buildWeb() {
  const compiled = buildJs();
  console.log("  1/3 src/EditorApp.rgr -> build/EditorApp.cjs");
  fs.rmSync(GEN, { recursive: true, force: true });
  fs.mkdirSync(GEN, { recursive: true });

  const cjs = fs.readFileSync(compiled, "utf8");
  const names = [...cjs.matchAll(/^module\.exports\.(\w+)\s*=/gm)].map((m) => m[1]);
  if (!names.includes("EditorApp")) {
    console.error("the compiled module does not export EditorApp");
    process.exit(4);
  }
  fs.writeFileSync(path.join(GEN, "app.js"), `// Generated by scripts/build-web.mjs — do not edit.
// SPDX-License-Identifier: MIT
const module = { exports: {} };
{
${cjs}
}
const AppModule = module.exports;
export default AppModule;
export const { ${names.join(", ")} } = AppModule;
`);
  fs.writeFileSync(path.join(GEN, "assets.js"), "// Generated by scripts/build-web.mjs — do not edit.\n" +
    `export const EDITOR_CSS = ${JSON.stringify(fs.readFileSync(path.join(ROOT, "assets", "editor.css"), "utf8"))};\n`);

  // EVG's helpers, followed transitively from what the page imports.
  const EVG = evgDir();
  const ENTRY = ["gl/evg-webgl.js", "gl/evg-measure.js"];
  const relativeImports = (text) => {
    const out = [];
    for (const m of text.matchAll(/(?:^|\s)(?:import|export)[^;]*?from\s*["'](\.[^"']+)["']/g)) out.push(m[1]);
    for (const m of text.matchAll(/import\s*\(\s*["'](\.[^"']+)["']\s*\)/g)) out.push(m[1]);
    return out;
  };
  const seen = new Set();
  const queue = [...ENTRY];
  while (queue.length) {
    const rel = queue.shift();
    if (seen.has(rel)) continue;
    const from = path.join(EVG, rel);
    if (!fs.existsSync(from)) {
      console.error(`the page imports ${rel}, which is not in the EVG package ${EVG}`);
      process.exit(4);
    }
    seen.add(rel);
    const to = path.join(GEN, "evg", rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    for (const next of relativeImports(fs.readFileSync(from, "utf8"))) {
      queue.push(path.posix.normalize(path.posix.join(path.posix.dirname(rel), next)));
    }
  }
  console.log(`  2/3 web/gen/app.js (${names.length} exports), ${seen.size} EVG helpers`);

  const fonts = path.join(GEN, "fonts");
  fs.mkdirSync(fonts, { recursive: true });
  for (const f of fs.readdirSync(path.join(ROOT, "native", "fonts"))) fs.copyFileSync(path.join(ROOT, "native", "fonts", f), path.join(fonts, f));
  const icon = path.join(ROOT, "native", "icon", "icon-1024.png");
  if (fs.existsSync(icon)) fs.copyFileSync(icon, path.join(GEN, "icon.png"));
  console.log("  3/3 web/gen/fonts, web/gen/assets.js");
}

if (import.meta.url === `file://${process.argv[1]}`) buildWeb();
