#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tero Tolonen (Carnivore; MIT licence text in desktop/LICENSE)
//
// Sliqtly Editor, native: src/EditorApp.rgr → C++ (Ranger), then one SDL2 +
// OpenGL binary with the host in native/ and EVG's native painter. After
// Carnivore's scripts/build-native.mjs (github.com/terotests/CarnivoreMusicPlayer, MIT).
//
//   node scripts/build-native.mjs [--run [args…]]
//
// Needs `npm install` (ranger-compiler), a C++17 compiler, SDL2 and libcurl:
//   macOS:          brew install sdl2           (Xcode command line tools; libcurl is part of macOS)
//   Debian/Ubuntu:  sudo apt-get install libsdl2-dev libgl-dev libcurl4-openssl-dev
// EVG is fetched from terotests/evg by `rgrc install` (scripts/ranger.mjs).
//
// Writes native/build/sliqtly-editor and native/build/fonts/; on macOS also
// native/build/Sliqtly Editor.app (with AppIcon.icns from native/icon/icon-1024.png).

import fs from "node:fs";
import path from "node:path";
import { execFileSync, execSync } from "node:child_process";
import { MAC, cxx, sdl2, glFlags, macFlags, macApp } from "./native-link.mjs";
import { ROOT, install, compile, evgDir } from "./ranger.mjs";

const NATIVE = path.join(ROOT, "native");
const BUILD = path.join(NATIVE, "build");
const argv = process.argv.slice(2);
const runAt = argv.indexOf("--run");
const APP_NAME = "Sliqtly Editor";
const BUNDLE_ID = "com.sliqtly.editor";
const VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8")).version;

const die = (msg) => { console.error(msg); process.exit(1); };
fs.mkdirSync(BUILD, { recursive: true });

// --- 1. Ranger → C++ -------------------------------------------------------------
install();
compile(["-l=cpp", "-nodecli", "src/EditorApp.rgr", `-d=${BUILD}`, "-o=EditorApp.cpp"], path.join(BUILD, "EditorApp.cpp"));
console.log("  1/3 src/EditorApp.rgr -> native/build/EditorApp.cpp");

// --- 2. The stylesheet, as C++ ---------------------------------------------------
const raw = (s) => {
  if (s.includes(")EVGP\"")) die("an asset contains the raw-string delimiter");
  return `R"EVGP(${s})EVGP"`;
};
fs.writeFileSync(path.join(BUILD, "assets.h"), `// Generated by scripts/build-native.mjs — do not edit.
#pragma once
static const char* EDITOR_CSS = ${raw(fs.readFileSync(path.join(ROOT, "assets", "editor.css"), "utf8"))};
`);
console.log("  2/3 assets/editor.css -> native/build/assets.h");

// --- 3. The binary ---------------------------------------------------------------
const { flags: sdl, framework } = sdl2();
const EVG_NATIVE = path.join(evgDir(), "native");
if (!fs.existsSync(path.join(EVG_NATIVE, "gl", "EvgGlPainter.h"))) die(`the EVG package has no native painter (${EVG_NATIVE}) — is ranger.json's evg rev new enough?`);
const sources = [
  ...["host.cpp", "platform.cpp", "http_curl.cpp", "oauth.cpp"].map((f) => path.join(NATIVE, f)),
  ...fs.readdirSync(path.join(EVG_NATIVE, "gl")).filter((f) => f.endsWith(".cpp")).map((f) => path.join(EVG_NATIVE, "gl", f)),
].map((f) => JSON.stringify(f)).join(" ");
const bin = path.join(BUILD, "sliqtly-editor");
// -w: the generated EditorApp.cpp is large and not written for warnings.
const cmd = `${cxx()} -std=c++17 ${macFlags(framework)}${process.env.CXX_OPT || "-O2"} -w -I${JSON.stringify(NATIVE)} -I${JSON.stringify(BUILD)} -I${JSON.stringify(EVG_NATIVE)} ${sources} -o ${JSON.stringify(bin)} ${sdl} ${glFlags()} -lcurl -lpthread`;
execSync(cmd, { stdio: "inherit" });
const fonts = path.join(BUILD, "fonts");
fs.mkdirSync(fonts, { recursive: true });
for (const f of fs.readdirSync(path.join(NATIVE, "fonts"))) fs.copyFileSync(path.join(NATIVE, "fonts", f), path.join(fonts, f));

if (MAC) {
  const { icon } = macApp({ nativeDir: NATIVE, buildDir: BUILD, name: APP_NAME, bundleId: BUNDLE_ID, version: VERSION, bin, exe: "sliqtly-editor", resources: [fonts], framework });
  console.log(`  3/3 native/build/sliqtly-editor, native/build/${APP_NAME}.app${icon ? "" : " (no icon: run npm run icon)"}${framework ? ", SDL2.framework inside" : ""}`);
} else {
  console.log("  3/3 native/build/sliqtly-editor");
}

if (runAt >= 0) {
  execFileSync(bin, argv.slice(runAt + 1), { stdio: "inherit" });
}
