[workspace]
members = ["sliqtly-bench","sliqtly-kernel","sliqtly-store"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Sliqtly Contributors"]
license = "MIT"
repository = "https://github.com/terotests/Sliqtly"

[profile.release]
debug = false
codegen-units = 4

[profile.profiling]
inherits = "release"
debug = true
