// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tero Tolonen
//
// Sliqtly, native: the browser editor's own app (src/PresApp.rgr with EVGUI,
// compiled to C++ by Ranger) in an SDL2 window, painted by EVG's native
// painter. web/main.js is the host it mirrors: this file does for a window
// what that file does for a page, in the same order, and asks the app
// everything else.
//
//   sliqtly-native [deck.md] [--server URL] [--token T] [--res DIR]
//                  [--size WxH] [--shot out.pam] [--script steps.txt]
//
// --server is the Sliqtly server whose presentations File → Presentations…
// lists, opens and saves to (REST API v1, docs/api-v1.md); without it
// SLIQTLY_SERVER, else http://localhost:8080 (`npm run serve`). "--server none"
// works on files only. --token (or SLIQTLY_TOKEN) is the server's -token.
// What the editor does with the server is src/PresServer.rgr; this file only
// performs its HTTP requests, on threads, with libcurl (http.h).
//
// --res is the folder with pres.css, the themes, the chrome stylesheets and
// the fonts (the build puts one beside the binary). --shot paints one frame
// (after --script, if any) into out.pam and quits: what the headless check
// drives. Script lines: "click x y", "type text", "key name", "wheel x y dx dy
// precise", "save", "request <app request>", "net" (waits for the server's
// answers). The check stays off the network unless --server is given.
//
// COORDINATES. The app works in window points, like CSS pixels: SDL's mouse
// and wheel positions are points too, so they go to the app unchanged. The
// framebuffer is in pixels (a Retina window has twice as many); only the
// painter sees those, through Frame::drawW/drawH. Mixing the two is the
// classic "the click lands beside the button" bug, so pointToApp() is the
// one conversion and it is the identity.
//
// SCROLLING. Wheels, trackpads and their glide go through PresScrollInput
// (src/PresScrollInput.rgr): the user's natural-scrolling setting is kept
// (SDL's FLIPPED flag is not applied), and a touchpad that leaves moving
// glides on where the platform sends no momentum of its own.

#include <SDL.h>

#include <chrono>
#include <cmath>
#include <ctime>
#include <deque>
#include <mutex>
#include <thread>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "PresApp.cpp"  // generated by Ranger from ../../src/PresApp.rgr
#include "gl/EvgGlPainter.h"
#include "http.h"

using evg::gl::Painter;
using EJ = evg::json::Value;

namespace {

std::string readText(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  std::stringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

bool writeText(const std::string& path, const std::string& text) {
  std::ofstream f(path, std::ios::binary);
  f << text;
  return (bool)f;
}

std::vector<uint8_t> readBytes(const std::string& path) {
  std::string s = readText(path);
  return std::vector<uint8_t>(s.begin(), s.end());
}

bool parse(const std::string& text, EJ& out) {
  out = EJ();
  return !text.empty() && evg::json::Parser(text).parse(out);
}

double num(const EJ* v, size_t i, double d = 0) {
  return (v && v->type == EJ::Arr && i < v->arr.size()) ? v->arr[i].num : d;
}

// The window point the app is given for an SDL position: the same point.
// SDL reports mouse, wheel and window sizes in points on every platform
// (SDL_WINDOW_ALLOW_HIGHDPI keeps it so on macOS); only the framebuffer is
// in pixels. Kept as a function so there is exactly one place it happens.
inline double pointToApp(int v) { return (double)v; }

const char* keyName(SDL_Keycode k) {
  switch (k) {
    case SDLK_BACKSPACE: return "backspace";
    case SDLK_RETURN:
    case SDLK_KP_ENTER: return "enter";
    case SDLK_TAB: return "tab";
    case SDLK_DELETE: return "delete";
    case SDLK_LEFT: return "left";
    case SDLK_RIGHT: return "right";
    case SDLK_UP: return "up";
    case SDLK_DOWN: return "down";
    case SDLK_HOME: return "home";
    case SDLK_END: return "end";
    case SDLK_PAGEUP: return "pageUp";
    case SDLK_PAGEDOWN: return "pageDown";
    case SDLK_ESCAPE: return "escape";
    default: return nullptr;
  }
}

// The CSS cursor names the app answers, as SDL's system cursors.
SDL_SystemCursor cursorFor(const std::string& css) {
  if (css == "pointer") return SDL_SYSTEM_CURSOR_HAND;
  if (css == "text") return SDL_SYSTEM_CURSOR_IBEAM;
  if (css == "ew-resize" || css == "col-resize") return SDL_SYSTEM_CURSOR_SIZEWE;
  if (css == "ns-resize" || css == "row-resize") return SDL_SYSTEM_CURSOR_SIZENS;
  if (css == "move" || css == "grab" || css == "grabbing") return SDL_SYSTEM_CURSOR_SIZEALL;
  if (css == "crosshair") return SDL_SYSTEM_CURSOR_CROSSHAIR;
  if (css == "not-allowed") return SDL_SYSTEM_CURSOR_NO;
  return SDL_SYSTEM_CURSOR_ARROW;
}

// Minutes east of UTC here, for the times the presentations window shows.
int utcOffsetMinutes() {
  std::time_t now = std::time(nullptr);
  std::tm local = *std::localtime(&now);
  std::tm utc = *std::gmtime(&now);
  utc.tm_isdst = local.tm_isdst;
  return (int)std::lround(std::difftime(std::mktime(&local), std::mktime(&utc)) / 60.0);
}

// PresServer's HTTP: each request on a thread of its own (http.h blocks),
// the answers handed back to the frame loop, which delivers them to the
// model. An SDL event wakes the loop when one arrives.
struct Net {
  struct Done {
    int id;
    long status;
    std::string body, error;
  };
  std::mutex lock;
  std::deque<Done> done;
  Uint32 wake = (Uint32)-1;

  void start(const ApiRequest& r) {
    std::vector<std::string> headers = r.headers;
    HttpOptions opts;
    opts.timeoutMs = r.timeoutMs;
    opts.insecure = r.insecure;
    int id = r.id;
    std::string method = r.method, url = r.url, body = r.body;
    std::thread([this, id, method, url, headers, body, opts] {
      HttpResponse res = httpRequest(method, url, headers, body, opts);
      {
        std::lock_guard<std::mutex> g(lock);
        done.push_back({id, res.status, std::move(res.body), std::move(res.error)});
      }
      if (wake != (Uint32)-1) {
        SDL_Event ev{};
        ev.type = wake;
        SDL_PushEvent(&ev);
      }
    }).detach();
  }

  std::deque<Done> take() {
    std::deque<Done> out;
    std::lock_guard<std::mutex> g(lock);
    out.swap(done);
    return out;
  }
};

struct Host {
  std::shared_ptr<PresApp> app;
  std::shared_ptr<PresScrollInput> scroll;
  std::shared_ptr<PresServer> server;
  Net net;
  Painter painter;
  SDL_Window* window = nullptr;
  int W = 1280, H = 800;          // window, points
  int drawW = 1280, drawH = 800;  // framebuffer, pixels
  std::string deckPath;
  bool needsPaint = true;
  std::string lastRev;
  std::string cursor = "default";
  std::map<SDL_SystemCursor, SDL_Cursor*> cursors;
  double mouseX = 0, mouseY = 0;
  bool mac = false;
  // the strip's slides, parsed once per layout revision
  std::string thumbsRev;
  std::map<int, EJ> thumbs;
  bool effectsRunning = false;
  double startS = 0;
  bool quit = false;

  double nowS() const {
    using namespace std::chrono;
    return duration<double>(steady_clock::now().time_since_epoch()).count();
  }

  bool mod(Uint16 km) const { return (km & (KMOD_CTRL | KMOD_GUI)) != 0; }

  void setCursor(const std::string& css) {
    if (css == cursor) return;
    cursor = css;
    SDL_SystemCursor id = cursorFor(css);
    if (!cursors[id]) cursors[id] = SDL_CreateSystemCursor(id);
    SDL_SetCursor(cursors[id]);
  }

  void sizes() {
    SDL_GetWindowSize(window, &W, &H);
    SDL_GL_GetDrawableSize(window, &drawW, &drawH);
  }

  // ⌘S / File → Save: a server's deck to the server; a deck opened from a
  // file to that file; the welcome deck, with a server, as a new one there.
  void save() {
    if (server->save(app->source())) return;
    if (deckPath.empty()) {
      if (server->connected()) server->create(app->docTitle(), app->source(), "");
      return;
    }
    if (writeText(deckPath, app->source())) {
      std::fprintf(stderr, "saved %s\n", deckPath.c_str());
    } else {
      std::fprintf(stderr, "could not save %s\n", deckPath.c_str());
    }
  }

  // What the app asked of the host (web/main.js handleRequests).
  void handleRequests() {
    for (std::string r = app->takeRequest(); !r.empty(); r = app->takeRequest()) handle(r);
  }

  void handle(const std::string& r) {
    if (server->request(r)) {
      needsPaint = true;
    } else if (r == "fullscreen") {
      SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);
    } else if (r == "click:save") {
      save();
    } else if (std::getenv("SLIQTLY_DEBUG")) {
      std::fprintf(stderr, "request not handled yet: %s\n", r.c_str());
    }
  }

  // --- painting (web/main.js paintOnce) ------------------------------------
  void drawList(EJ& doc, float ox, float oy, float s, bool clear, double t) {
    evg::gl::Frame f;
    f.pageW = W;
    f.pageH = H;
    f.drawW = drawW;
    f.drawH = drawH;
    f.ox = ox;
    f.oy = oy;
    f.scale = s;
    f.clear = clear;
    f.time = (float)t;
    const EJ* list = doc.get("list");
    painter.draw(list ? *list : doc, f);
  }

  void drawJson(const std::string& j, float ox, float oy, float s, double t) {
    EJ doc;
    if (parse(j, doc)) drawList(doc, ox, oy, s, false, t);
  }

  void paint() {
    double t = nowS() - startS;
    EJ layout;
    parse(app->layoutJson(), layout);
    std::string rev = layout.strOr("rev", "");
    if (const EJ* rv = layout.get("rev")) {
      if (rv->type == EJ::Num) rev = std::to_string(rv->num);
    }
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    EJ chrome;
    parse(app->chromeJson(), chrome);
    drawList(chrome, 0, 0, 1, true, t);
    effectsRunning = false;
    const EJ* stage = layout.get("stage");
    bool present = layout.strOr("mode", "") == "present";
    if (layout.numOr("slides", 0) > 0 && stage) {
      EJ st;
      if (parse(app->stageJson(), st)) {
        const EJ* l = st.get("list");
        const EJ* fx = l ? l->get("effects") : nullptr;
        effectsRunning = fx && fx->type == EJ::Arr && !fx->arr.empty();
        drawList(st, (float)num(stage, 0), (float)num(stage, 1), (float)num(stage, 2, 1), false, t);
      }
      std::string ij = app->inkJson();
      if (!ij.empty()) drawJson(ij, (float)num(stage, 0), (float)num(stage, 1), (float)num(stage, 2, 1), t);
    }
    if (layout.numOr("slides", 0) > 0 && !present) {
      std::string pj = app->pickJson();
      if (!pj.empty()) drawJson(pj, 0, 0, 1, t);
    }
    if (rev != thumbsRev) {
      thumbs.clear();
      thumbsRev = rev;
    }
    const EJ* strip = layout.get("strip");
    if (const EJ* th = layout.get("thumbs")) {
      for (const EJ& row : th->arr) {
        int i = (int)num(&row, 0);
        float x = (float)num(&row, 1), y = (float)num(&row, 2), s = (float)num(&row, 3);
        bool cut = num(&row, 5) != 0 || (row.arr.size() > 5 && row.arr[5].type == EJ::Bool && row.arr[5].b);
        auto it = thumbs.find(i);
        if (it == thumbs.end()) {
          EJ doc;
          parse(app->slideJson(i), doc);
          it = thumbs.emplace(i, std::move(doc)).first;
        }
        if (cut && strip) {
          // cut by the strip's edge: a clip at the edge, in the slide's units
          EJ doc = it->second;
          EJ* list = doc.type == EJ::Obj && doc.obj.count("list") ? &doc.obj["list"] : &doc;
          EJ& cmds = list->obj["cmds"];
          EJ push, pop;
          push.type = pop.type = EJ::Obj;
          auto n = [](double v) { EJ e; e.type = EJ::Num; e.num = v; return e; };
          push.obj["k"] = n(4);
          push.obj["x"] = n((num(strip, 0) - x) / s);
          push.obj["y"] = n((num(strip, 1) - y) / s);
          push.obj["w"] = n(num(strip, 2) / s);
          push.obj["h"] = n(num(strip, 3) / s);
          pop.obj["k"] = n(5);
          cmds.arr.insert(cmds.arr.begin(), push);
          cmds.arr.push_back(pop);
          drawList(doc, x, y, s, false, 2.0);
        } else {
          drawList(it->second, x, y, s, false, 2.0);
        }
      }
    }
    // the surfaces over the chrome, bottom first (PresApp.layerOrder)
    std::string order = app->layerOrder();
    size_t a = 0;
    while (a <= order.size()) {
      size_t b = order.find(',', a);
      if (b == std::string::npos) b = order.size();
      std::string layer = order.substr(a, b - a);
      a = b + 1;
      if (layer == "bar") drawJson(app->toolbarJson(), 0, 0, 1, t);
      else if (layer == "sketch") drawJson(app->sketchJson(), 0, 0, 1, t);
      else if (layer == "room") drawJson(app->roomJson(), 0, 0, 1, t);
      else if (layer == "review") drawJson(app->reviewJson(), 0, 0, 1, t);
      else if (layer == "hint") drawJson(app->hintJson(), 0, 0, 1, t);
      else if (layer == "chart") {
        EJ cj;
        if (parse(app->chartJson(), cj)) drawList(cj, (float)cj.numOr("x", 0), (float)cj.numOr("y", 0), 1, false, t);
      } else if (layer == "panels") drawJson(app->panelsPartJson("docked"), 0, 0, 1, t);
      else if (layer == "dialog") drawJson(app->panelsPartJson("dialog"), 0, 0, 1, t);
      else if (layer == "toast") drawJson(app->panelsPartJson("toast"), 0, 0, 1, t);
    }
  }

  // --- input -----------------------------------------------------------------
  void pointerDown(double x, double y, bool shift, int clicks, Uint16 km) {
    scroll->halt();
    app->setDragSlop(6);
    app->setTouch(false);
    // ⌘ on a Mac, Ctrl elsewhere: the pick-and-add key
    app->setCtrl(mac ? (km & KMOD_GUI) != 0 : (km & KMOD_CTRL) != 0);
    app->pointerDown(x, y, shift, std::min(clicks, 3));
    needsPaint = true;
  }

  void wheel(double x, double y, double ux, double uy, bool flipped, bool precise, Uint16 km) {
    // a pinch on a trackpad, or Ctrl + wheel, over the slide sees it closer
    if ((km & KMOD_CTRL) && app->canZoomAt(x, y)) {
      app->viewPinch(x, y, std::exp(uy * 0.1), 0, 0);
      needsPaint = true;
      return;
    }
    scroll->sdlWheel(x, y, ux, uy, flipped, precise);
    if (app->wheelXY(scroll->atX, scroll->atY, scroll->outX, scroll->outY)) needsPaint = true;
  }

  void key(const SDL_KeyboardEvent& k) {
    Uint16 km = k.keysym.mod;
    bool shift = (km & KMOD_SHIFT) != 0;
    bool m = mod(km);
    SDL_Keycode code = k.keysym.sym;
    bool presenting = false;
    {
      EJ layout;
      if (parse(app->layoutJson(), layout)) presenting = layout.strOr("mode", "") == "present";
    }
    if (code == SDLK_F5) {
      app->present(!shift);
    } else if (!presenting && m && (code == SDLK_RETURN || code == SDLK_KP_ENTER)) {
      if (app->isPlaying()) app->stop();
      else app->play();
    } else if (const char* name = keyName(code)) {
      app->key(name, shift, m);
    } else if (m && code == SDLK_c) {
      std::string s = app->copySelection();
      if (!s.empty()) SDL_SetClipboardText(s.c_str());
    } else if (m && code == SDLK_x) {
      std::string s = app->cutSelection();
      if (!s.empty()) SDL_SetClipboardText(s.c_str());
    } else if (m && code == SDLK_v) {
      if (char* s = SDL_GetClipboardText()) {
        if (*s) app->pasteText(s);
        SDL_free(s);
      }
    } else if ((km & KMOD_CTRL) && !(km & KMOD_GUI) && code == SDLK_m) {
      app->request("slide:new");
    } else if (m && code == SDLK_d) {
      app->request("slide:duplicate");
    } else if (m && code == SDLK_s) {
      save();
    } else if (m && (code == SDLK_z || code == SDLK_y || code == SDLK_a)) {
      char ch[2] = {(char)code, 0};
      app->chord(ch);
    }
    needsPaint = true;
  }

  void event(const SDL_Event& ev) {
    switch (ev.type) {
      case SDL_QUIT: quit = true; break;
      default:
        if (ev.type == net.wake) needsPaint = true;
        break;
      case SDL_WINDOWEVENT:
        if (ev.window.event == SDL_WINDOWEVENT_SIZE_CHANGED || ev.window.event == SDL_WINDOWEVENT_RESIZED) {
          sizes();
          app->setPageSize(W, H);
          thumbs.clear();
        }
        if (ev.window.event == SDL_WINDOWEVENT_LEAVE) app->pointerLeft();
        needsPaint = true;
        break;
      case SDL_MOUSEMOTION: {
        if (ev.motion.which == SDL_TOUCH_MOUSEID) break;
        mouseX = pointToApp(ev.motion.x);
        mouseY = pointToApp(ev.motion.y);
        app->pointerMove(mouseX, mouseY);
        setCursor(app->cursorAt(mouseX, mouseY));
        if (ev.motion.state) needsPaint = true;
        break;
      }
      case SDL_MOUSEBUTTONDOWN: {
        if (ev.button.which == SDL_TOUCH_MOUSEID) break;
        double x = pointToApp(ev.button.x), y = pointToApp(ev.button.y);
        Uint16 km = SDL_GetModState();
        bool secondary = ev.button.button == SDL_BUTTON_RIGHT || (mac && ev.button.button == SDL_BUTTON_LEFT && (km & KMOD_CTRL));
        if (secondary && app->inStrip(x, y)) {
          app->slideMenuAt(x, y);
          needsPaint = true;
          break;
        }
        if (ev.button.button == SDL_BUTTON_LEFT) pointerDown(x, y, (km & KMOD_SHIFT) != 0, ev.button.clicks, km);
        break;
      }
      case SDL_MOUSEBUTTONUP:
        if (ev.button.which == SDL_TOUCH_MOUSEID) break;
        if (ev.button.button == SDL_BUTTON_LEFT) {
          app->pointerUp();
          needsPaint = true;
        }
        break;
      case SDL_MOUSEWHEEL: {
        if (ev.wheel.which == SDL_TOUCH_MOUSEID) break;
#if SDL_VERSION_ATLEAST(2, 0, 18)
        double ux = ev.wheel.preciseX, uy = ev.wheel.preciseY;
#else
        double ux = ev.wheel.x, uy = ev.wheel.y;
#endif
        // SDL 2 does not say which device scrolled. A touchpad's smooth
        // scroll arrives in fractions of a unit, a wheel's notch as whole
        // ones: that is what tells a stream that may glide from one that may not.
        bool precise = ux != std::floor(ux) || uy != std::floor(uy);
#if SDL_VERSION_ATLEAST(2, 26, 0)
        double x = pointToApp(ev.wheel.mouseX), y = pointToApp(ev.wheel.mouseY);
#else
        double x = mouseX, y = mouseY;
#endif
        wheel(x, y, ux, uy, ev.wheel.direction == SDL_MOUSEWHEEL_FLIPPED, precise, SDL_GetModState());
        break;
      }
      case SDL_FINGERDOWN:
      case SDL_FINGERMOTION:
      case SDL_FINGERUP: {
        // a finger is a press the app reads as a touch (web/main.js: setTouch,
        // a wider drag slop); SDL's own mouse copy of it is ignored above
        double x = ev.tfinger.x * W, y = ev.tfinger.y * H;
        if (ev.type == SDL_FINGERDOWN) {
          scroll->halt();
          app->setDragSlop(16);
          app->setTouch(true);
          app->pointerDown(x, y, false, 1);
        } else if (ev.type == SDL_FINGERMOTION) {
          app->pointerMove(x, y);
        } else {
          app->pointerUp();
        }
        needsPaint = true;
        break;
      }
      case SDL_TEXTINPUT:
        // ⌘ / Ctrl + a letter is a shortcut (key() above), not text
        if (!mod(SDL_GetModState())) {
          app->text(ev.text.text);
          needsPaint = true;
        }
        break;
      case SDL_KEYDOWN:
        key(ev.key);
        break;
    }
  }

  // One frame: the clock, a glide, and a paint when anything changed
  // (web/main.js frame()).
  // The server's requests out, its answers in, and what they mean for the
  // editor applied (PresServer's host fields).
  void network() {
    for (auto r = server->api->take(); r.has_value(); r = server->api->take()) net.start(**r);
    std::deque<Net::Done> ready = net.take();
    for (auto& d : ready) server->api->deliver(d.id, (int)d.status, d.body, d.error);
    if (!ready.empty()) server->process();
    if (server->loadPending) {
      server->loadPending = false;
      app->setSource(server->loadMd);
      server->loadMd = "";
      deckPath = "";
      SDL_SetWindowTitle(window, ("Sliqtly – " + server->deckName).c_str());
      needsPaint = true;
    }
    if (server->decksPending) {
      server->decksPending = false;
      if (server->decksOpen) {
        server->decksOpen = false;
        app->openDecks(server->decksJson);
      } else {
        app->setDecks(server->decksJson);
      }
      needsPaint = true;
    }
    if (server->decksOpen && !server->decksJson.empty()) {
      server->decksOpen = false;
      app->openDecks(server->decksJson);
      needsPaint = true;
    }
    for (auto& n : server->notes) {
      app->toast(n);
      std::fprintf(stderr, "%s\n", n.c_str());
    }
    if (!server->notes.empty()) {
      server->notes.clear();
      needsPaint = true;
    }
    if (!server->askKey.empty()) {
      app->openChoice(server->askKey, server->askTitle, server->askText, server->askOk, server->askAlt);
      server->askKey = "";
      needsPaint = true;
    }
  }

  void frame(double dtMs) {
    network();
    double now = nowS();
    app->setUiTime(now);
    if (app->uiBusy()) needsPaint = true;
    if (app->settle()) needsPaint = true;
    if (app->isPlaying()) {
      app->setTime(app->currentTime() + dtMs / 1000.0);
      needsPaint = true;
    }
    if (scroll->tick(dtMs)) {
      if (app->wheelXY(scroll->atX, scroll->atY, scroll->outX, scroll->outY)) needsPaint = true;
    }
    std::string rev = app->revision();
    if (needsPaint || rev != lastRev || effectsRunning) {
      needsPaint = false;
      lastRev = rev;
      paint();
      handleRequests();
      SDL_GL_SwapWindow(window);
    }
  }

  bool busy() { return needsPaint || effectsRunning || scroll->gliding() || app->isPlaying() || app->uiBusy(); }
};

std::vector<std::string> splitWords(const std::string& line) {
  std::vector<std::string> out;
  std::istringstream is(line);
  std::string w;
  while (is >> w) out.push_back(w);
  return out;
}

// A scripted step, for the headless check.
void runStep(Host& h, const std::string& line) {
  auto w = splitWords(line);
  if (w.empty()) return;
  if (w[0] == "click" && w.size() >= 3) {
    double x = std::atof(w[1].c_str()), y = std::atof(w[2].c_str());
    h.pointerDown(x, y, false, 1, 0);
    h.app->pointerUp();
  } else if (w[0] == "type") {
    h.app->text(line.substr(line.find("type") + 5));
  } else if (w[0] == "key" && w.size() >= 2) {
    h.app->key(w[1], false, false);
  } else if (w[0] == "wheel" && w.size() >= 6) {
    h.wheel(std::atof(w[1].c_str()), std::atof(w[2].c_str()), std::atof(w[3].c_str()), std::atof(w[4].c_str()), false,
            w[5] == "1", 0);
  } else if (w[0] == "frame") {
    h.paint();
  } else if (w[0] == "save") {
    h.save();
  } else if (w[0] == "request" && w.size() >= 2) {
    h.handle(w[1]);
  } else if (w[0] == "net") {
    // the app's requests, then the server's answers, until it has none
    // pending (at most ten seconds)
    h.paint();
    h.handleRequests();
    for (int i = 0; i < 1000; i++) {
      h.network();
      if (!h.server->api->busy()) break;
      SDL_Delay(10);
    }
    h.network();
    h.paint();
  }
  h.needsPaint = true;
}

}  // namespace

int main(int argc, char** argv) {
  std::string res, shot, script, size;
  const char* envServer = std::getenv("SLIQTLY_SERVER");
  const char* envToken = std::getenv("SLIQTLY_TOKEN");
  std::string serverUrl = envServer && *envServer ? envServer : "http://localhost:8080";
  std::string token = envToken ? envToken : "";
  bool serverGiven = false;
  std::string deck;
  for (int i = 1; i < argc; i++) {
    std::string a = argv[i];
    if (a == "--res" && i + 1 < argc) res = argv[++i];
    else if (a == "--shot" && i + 1 < argc) shot = argv[++i];
    else if (a == "--script" && i + 1 < argc) script = argv[++i];
    else if (a == "--size" && i + 1 < argc) size = argv[++i];
    else if (a == "--server" && i + 1 < argc) serverUrl = argv[++i], serverGiven = true;
    else if (a == "--token" && i + 1 < argc) token = argv[++i];
    else deck = a;
  }
  if (res.empty()) {
    // beside the binary (and inside the .app's Resources on a Mac)
    char* base = SDL_GetBasePath();
    res = std::string(base ? base : "./") + "editor-res";
    if (base) SDL_free(base);
  }
  if (!res.empty() && res.back() != '/') res += "/";

  Host h;
#if defined(__APPLE__)
  h.mac = true;
#endif
  if (!size.empty()) std::sscanf(size.c_str(), "%dx%d", &h.W, &h.H);

  SDL_SetHint(SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH, "1");
  if (SDL_Init(SDL_INIT_VIDEO) != 0) {
    std::fprintf(stderr, "SDL_Init: %s\n", SDL_GetError());
    return 1;
  }
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
  SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
#if defined(__APPLE__)
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);
#endif
  Uint32 flags = SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI;
  if (!shot.empty()) flags |= SDL_WINDOW_HIDDEN;
  h.window = SDL_CreateWindow("Sliqtly", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, h.W, h.H, flags);
  SDL_GLContext ctx = h.window ? SDL_GL_CreateContext(h.window) : nullptr;
  if (!ctx) {
    std::fprintf(stderr, "no OpenGL 3.3 context: %s\n", SDL_GetError());
    return 1;
  }
  SDL_GL_SetSwapInterval(1);
  h.sizes();

  // the faces the app measures with, registered with the painter too
  struct FaceFile { const char* app; const char* family; bool bold, italic; const char* file; };
  const FaceFile faces[] = {
      {"Open Sans", "Open Sans", false, false, "OpenSans-Regular.ttf"},
      {"Open Sans-Bold", "Open Sans", true, false, "OpenSans-Bold.ttf"},
      {"Open Sans-Italic", "Open Sans", false, true, "OpenSans-Italic.ttf"},
      {"Open Sans-BoldItalic", "Open Sans", true, true, "OpenSans-BoldItalic.ttf"},
      {"Noto Sans", "Noto Sans", false, false, "NotoSans-Regular.ttf"},
      {"Noto Sans-Bold", "Noto Sans", true, false, "NotoSans-Bold.ttf"},
  };
  std::string err;
  for (const FaceFile& f : faces) h.painter.text().addFaceFile(f.family, f.bold, f.italic, res + "fonts/" + f.file, &err);
  // symbols the text faces lack (▶, ⏮, arrows, boxes) come from these
  h.painter.text().addFaceFile("DejaVu Sans Mono", false, false, res + "fonts/DejaVuSansMono.ttf", &err);
  h.painter.text().addFaceFile("DejaVu Sans Mono", true, false, res + "fonts/DejaVuSansMono-Bold.ttf", &err);
  if (!h.painter.init(err)) {
    std::fprintf(stderr, "painter: %s\n", err.c_str());
    return 1;
  }

  h.app = std::make_shared<PresApp>();
  h.scroll = std::make_shared<PresScrollInput>();
  // macOS sends a trackpad's glide itself; SDL hands a precise scroll on to
  // us at a tenth of the pixels it moved
  h.scroll->osMomentum = h.mac;
  h.scroll->pxPerUnit = h.mac ? 10.0 : 40.0;
  std::string kit = readText(res + "base.css"), chart = readText(res + "chart-editor.css");
  h.app->setChartCss(kit + "\n" + chart);
  h.app->setHintCss(kit + "\n" + chart + "\n" + readText(res + "hint.css"));
  h.app->setPanelsCss(kit + "\n" + readText(res + "panels.css"));
  h.app->setToolbarCss(kit + "\n" + readText(res + "toolbar.css"));
  h.app->useDeckTabs(true);
  h.app->useToolbar(true);
  h.app->init(readText(res + "pres.css"), h.W, h.H);
  for (const FaceFile& f : faces) {
    auto b = readBytes(res + "fonts/" + f.file);
    if (!b.empty()) h.app->attachFont(f.app, b);
  }
  // what the app cannot measure with an attached face, the painter does,
  // in the face it will draw it with
  Painter* painter = &h.painter;
  h.app->setPlatformMeasure([painter](std::string text, std::string family, double sz) {
    return painter->text().measure(family, sz, text);
  });
  for (const char* t : {"aurora", "nebula", "carbon", "ember", "midnight", "corporate", "editorial"}) {
    std::string css = readText(res + "themes/" + t + ".css");
    if (!css.empty()) h.app->addTemplate(t, css);
  }
  h.app->setStyleSheet(readText(res + "themes/aurora.css"));
  h.deckPath = deck.empty() ? "" : deck;
  std::string md = deck.empty() ? readText(res + "welcome.en.md") : readText(deck);
  h.app->setSource(md);
  h.app->setPageSize(h.W, h.H);
  h.startS = h.nowS();
  SDL_StartTextInput();
  h.server = std::make_shared<PresServer>();
  h.server->utcOffsetMin = utcOffsetMinutes();
  h.net.wake = SDL_RegisterEvents(1);
  // the headless check stays off the network unless told otherwise
  if ((shot.empty() || serverGiven) && serverUrl != "none") h.server->connect(serverUrl, token);

  if (!script.empty()) {
    // the app places its parts when it is painted: a step before the first
    // frame would press where nothing has been laid out yet
    h.paint();
    std::istringstream lines(readText(script));
    std::string line;
    while (std::getline(lines, line)) runStep(h, line);
  }
  if (!shot.empty()) {
    h.paint();
    std::vector<unsigned char> px((size_t)h.drawW * h.drawH * 4);
    glReadPixels(0, 0, h.drawW, h.drawH, GL_RGBA, GL_UNSIGNED_BYTE, px.data());
    std::ofstream f(shot, std::ios::binary);
    f << "P7\nWIDTH " << h.drawW << "\nHEIGHT " << h.drawH << "\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n";
    for (int y = h.drawH - 1; y >= 0; y--) f.write((const char*)px.data() + (size_t)y * h.drawW * 4, h.drawW * 4);
    std::printf("%s: %dx%d\n", shot.c_str(), h.drawW, h.drawH);
    return 0;
  }

  double last = h.nowS();
  while (!h.quit) {
    SDL_Event ev;
    // asleep until something happens, unless something is moving
    if (h.busy() ? SDL_PollEvent(&ev) : SDL_WaitEventTimeout(&ev, 250)) {
      do h.event(ev);
      while (SDL_PollEvent(&ev));
    }
    double now = h.nowS();
    h.frame((now - last) * 1000.0);
    last = now;
  }
  SDL_GL_DeleteContext(ctx);
  SDL_DestroyWindow(h.window);
  SDL_Quit();
  return 0;
}
