// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tero Tolonen (Carnivore; MIT licence text in desktop/LICENSE)
//
// Sliqtly Editor, native: the same EditorApp (src/EditorApp.rgr, compiled to
// C++ by Ranger) in an SDL2 window, drawn with OpenGL by EVG's native painter
// (<evg>/native/gl, from the EVG package `rgrc install` fetched). The pattern
// is Carnivore's host (github.com/terotests/CarnivoreMusicPlayer, MIT,
// native/host.cpp): this file owns what an operating system has and Ranger
// does not, and asks the app everything else.
//
//   the window, the pointer, the keys, text input (UTF-8), the clipboard
//   the network      libcurl on worker threads, for the requests the app
//                    queues (takeRequest / deliver); a pinned CA per server
//   the settings     settings.json in the settings folder, readable by the
//                    user only (tokens are in it)
//   signing in       the OAuth loopback (oauth.h) and the system browser
//   the pixels       the app's display list, then the server's display list
//                    of the current slide in the preview rectangle the app
//                    reports (an offscreen target, blitted into place)
//
//   sliqtly-editor [--script file] [--seconds S --shot out.pam] [--size WxH]
//                  [--icon out.pam]
//
// --script runs the app's scripted steps (EditorApp.runScript: what
// scripts/check-native.mjs drives); "shot <file>" there writes the next
// frame as a PAM image. --icon writes the 1024 px application icon and quits.
// SLIQTLY_DEBUG=1 prints the app's state as it changes; SLIQTLY_EDITOR_CONFIG
// puts the settings elsewhere; SLIQTLY_NO_BROWSER prints the sign-in address
// instead of opening a browser.

#include <SDL.h>

#include <atomic>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdio>
#include <cstring>
#include <deque>
#include <filesystem>
#include <fstream>
#include <functional>
#include <memory>
#include <mutex>
#include <sstream>
#include <thread>

#include "EditorApp.cpp"  // generated by Ranger from ../src/EditorApp.rgr
#include "assets.h"       // generated: assets/editor.css
#include "gl/EvgGlPainter.h"
#include "http.h"
#include "oauth.h"
#include "platform.h"
#include "sha256.h"

namespace {

using evg::gl::Painter;
using EJ = evg::json::Value;  // EVG's JSON (JVal is the app's own class)

std::shared_ptr<EditorApp> app;
SDL_Window* window = nullptr;
bool quit = false;
bool scriptFailed = false;
std::string configDir;

bool debugOn() { return std::getenv("SLIQTLY_DEBUG") != nullptr; }

double epochMs() {
  return (double)std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
}

// --- the network: a few worker threads, answers collected for the frame loop ----
struct Job {
  int id = 0;
  std::string method, url, body;
  std::vector<std::string> headers;
  HttpOptions opts;
};
struct Done {
  int id = 0;
  long status = 0;
  std::string body, error;
};

class Workers {
 public:
  explicit Workers(int n) {
    for (int i = 0; i < n; i++) threads_.emplace_back([this] { loop(); });
  }
  ~Workers() {
    {
      std::lock_guard<std::mutex> g(lock_);
      stop_ = true;
    }
    wake_.notify_all();
    for (auto& t : threads_) t.join();
  }
  void submit(std::function<void()> job) {
    {
      std::lock_guard<std::mutex> g(lock_);
      jobs_.push_back(std::move(job));
      pending_++;
    }
    wake_.notify_one();
  }
  int pending() const { return pending_.load(); }

 private:
  void loop() {
    for (;;) {
      std::function<void()> job;
      {
        std::unique_lock<std::mutex> g(lock_);
        wake_.wait(g, [this] { return stop_ || !jobs_.empty(); });
        if (stop_ && jobs_.empty()) return;
        job = std::move(jobs_.front());
        jobs_.pop_front();
      }
      job();
      pending_--;
    }
  }
  std::vector<std::thread> threads_;
  std::deque<std::function<void()>> jobs_;
  std::mutex lock_;
  std::condition_variable wake_;
  bool stop_ = false;
  std::atomic<int> pending_{0};
};

std::mutex doneLock;
std::deque<Done> done;
std::deque<std::function<void()>> mainQueue;  // results that are not HTTP answers (CA pinning)

void postMain(std::function<void()> fn) {
  std::lock_guard<std::mutex> g(doneLock);
  mainQueue.push_back(std::move(fn));
}

std::string caFileFor(const std::string& fp) {
  if (fp.empty()) return "";
  return configDir + "/ca/" + fp + ".pem";
}

std::vector<std::string> splitLines(const std::string& s) {
  std::vector<std::string> out;
  std::stringstream ss(s);
  std::string line;
  while (std::getline(ss, line)) {
    if (!line.empty()) out.push_back(line);
  }
  return out;
}

void startRequest(Workers& workers, int id) {
  Job j;
  j.id = id;
  j.method = app->reqMethod(id);
  j.url = app->reqUrl(id);
  j.body = app->reqBody(id);
  j.headers = splitLines(app->reqHeaders(id));
  j.opts.timeoutMs = app->reqTimeoutMs(id);
  j.opts.insecure = app->reqInsecure(id);
  std::string ca = caFileFor(app->reqCa(id));
  if (!ca.empty() && std::filesystem::exists(ca)) j.opts.caFile = ca;
  if (debugOn()) std::fprintf(stderr, "http: %s %s%s\n", j.method.c_str(), j.url.c_str(), j.opts.caFile.empty() ? "" : " (pinned CA)");
  workers.submit([j] {
    HttpResponse r = httpRequest(j.method, j.url, j.headers, j.body, j.opts);
    std::lock_guard<std::mutex> g(doneLock);
    done.push_back({j.id, r.status, r.body, r.error});
  });
}

// Fetch <server>/ca.crt without verifying (it is what is being verified),
// check its SHA-256 against the fingerprint the user accepted, keep it.
void pinCa(Workers& workers, const std::string& url, const std::string& fingerprint) {
  workers.submit([url, fingerprint] {
    HttpOptions o;
    o.insecure = true;
    o.timeoutMs = 15000;
    HttpResponse r = httpRequest("GET", url, {}, "", o);
    std::string want;
    for (char c : fingerprint) {
      if (c == ':') continue;
      want += (char)std::tolower((unsigned char)c);
    }
    bool ok = false;
    std::string why;
    if (r.status != 200) {
      why = r.status == 0 ? r.error : "HTTP " + std::to_string(r.status);
    } else {
      std::string der = sq::pemFirstCertificateDer(r.body);
      std::string got = der.empty() ? "" : sq::hex(sq::Sha256::digest(der));
      if (der.empty()) {
        why = "the answer is not a PEM certificate";
      } else if (got != want) {
        why = "its fingerprint is " + got + ", not the one accepted";
      } else {
        std::error_code ec;
        std::filesystem::create_directories(configDir + "/ca", ec);
        platformPrivateDir(configDir + "/ca");
        ok = platformWritePrivate(caFileFor(want), r.body);
        if (!ok) why = "cannot write it to " + caFileFor(want);
      }
    }
    postMain([want, ok, why] { app->caResult(want, ok, why); });
  });
}

// --- settings --------------------------------------------------------------------
std::string settingsPath() { return configDir + "/settings.json"; }

// --- text ------------------------------------------------------------------------
std::string fontDir() {
  std::string base;
  if (char* b = SDL_GetBasePath()) {
    base = b;
    SDL_free(b);
  }
  for (std::string dir : {base + "fonts", base + "../Resources/fonts", std::string("fonts")}) {
    if (std::filesystem::exists(dir + "/NotoSans-Regular.ttf")) return dir;
  }
  return base + "fonts";
}

void addFaces(Painter& painter) {
  struct F { const char* family; bool bold, italic; const char* file; };
  const F faces[] = {
      {"Noto Sans", false, false, "NotoSans-Regular.ttf"},
      {"Noto Sans", true, false, "NotoSans-Bold.ttf"},
      {"DejaVu Sans Mono", false, false, "DejaVuSansMono.ttf"},
      {"DejaVu Sans Mono", true, false, "DejaVuSansMono-Bold.ttf"},
      {"Open Sans", false, false, "OpenSans-Regular.ttf"},
      {"Open Sans", true, false, "OpenSans-Bold.ttf"},
      {"Open Sans", false, true, "OpenSans-Italic.ttf"},
      {"Open Sans", true, true, "OpenSans-BoldItalic.ttf"},
  };
  std::string dir = fontDir(), err;
  for (const F& f : faces) {
    if (!painter.text().addFaceFile(f.family, f.bold, f.italic, dir + "/" + f.file, &err)) std::fprintf(stderr, "sliqtly-editor: %s\n", err.c_str());
  }
}

// --- pixels ----------------------------------------------------------------------
void writePam(const std::string& path, const std::vector<unsigned char>& rgbaTopDown, int w, int h) {
  std::ofstream f(path, std::ios::binary);
  f << "P7\nWIDTH " << w << "\nHEIGHT " << h << "\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n";
  f.write((const char*)rgbaTopDown.data(), (std::streamsize)rgbaTopDown.size());
}

// The window's framebuffer as it is now, top row first.
void shotWindow(const std::string& path, int w, int h) {
  std::vector<unsigned char> rgba((size_t)w * h * 4), flipped((size_t)w * h * 4);
  glBindFramebuffer(GL_READ_FRAMEBUFFER, 0);
  glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, rgba.data());
  for (int y = 0; y < h; y++) std::memcpy(&flipped[(size_t)y * w * 4], &rgba[(size_t)(h - 1 - y) * w * 4], (size_t)w * 4);
  for (size_t i = 3; i < flipped.size(); i += 4) flipped[i] = 255;
  writePam(path, flipped, w, h);
}

// The application icon, `size` px, straight alpha, top row first.
std::vector<unsigned char> paintIcon(Painter& painter, int size) {
  EJ list;
  evg::json::Parser(app->iconDisplayListJson((double)size)).parse(list);
  evg::gl::Target target;
  target.ensure(size, size, 4);
  target.bind();
  painter.draw(list, {size, size, size, size, 0.f, nullptr});
  std::vector<unsigned char> px = target.readPixels();
  for (size_t i = 0; i + 3 < px.size(); i += 4) {
    unsigned a = px[i + 3];
    for (int c = 0; c < 3; c++) px[i + c] = a ? (unsigned char)std::min(255u, px[i + c] * 255u / a) : 0;
  }
  return px;
}

void setWindowIcon(const std::vector<unsigned char>& rgba, int size) {
  SDL_Surface* s = SDL_CreateRGBSurfaceWithFormat(0, size, size, 32, SDL_PIXELFORMAT_RGBA32);
  if (!s) return;
  SDL_LockSurface(s);
  for (int y = 0; y < size; y++) std::memcpy((Uint8*)s->pixels + (size_t)y * s->pitch, &rgba[(size_t)y * size * 4], (size_t)size * 4);
  SDL_UnlockSurface(s);
  SDL_SetWindowIcon(window, s);
  SDL_FreeSurface(s);
}

const char* keyName(SDL_Keycode k) {
  switch (k) {
    case SDLK_LEFT: return "Left";
    case SDLK_RIGHT: return "Right";
    case SDLK_UP: return "Up";
    case SDLK_DOWN: return "Down";
    case SDLK_HOME: return "Home";
    case SDLK_END: return "End";
    case SDLK_PAGEUP: return "PageUp";
    case SDLK_PAGEDOWN: return "PageDown";
    case SDLK_RETURN:
    case SDLK_KP_ENTER: return "Enter";
    case SDLK_BACKSPACE: return "Backspace";
    case SDLK_DELETE: return "Delete";
    case SDLK_TAB: return "Tab";
    case SDLK_ESCAPE: return "Escape";
    case SDLK_F5: return "F5";
    default: return nullptr;
  }
}

}  // namespace

int main(int argc, char** argv) {
  double maxSeconds = -1;
  std::string shotAtEnd, iconOut, scriptFile;
  int startW = 1280, startH = 800;
  for (int i = 1; i < argc; i++) {
    std::string a = argv[i];
    if (a == "--seconds" && i + 1 < argc) maxSeconds = std::atof(argv[++i]);
    else if (a == "--shot" && i + 1 < argc) shotAtEnd = argv[++i];
    else if (a == "--icon" && i + 1 < argc) iconOut = argv[++i];
    else if (a == "--script" && i + 1 < argc) scriptFile = argv[++i];
    else if (a == "--size" && i + 1 < argc) std::sscanf(argv[++i], "%dx%d", &startW, &startH);
  }

  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS) != 0) {
    std::fprintf(stderr, "sliqtly-editor: SDL_Init: %s\n", SDL_GetError());
    return 1;
  }
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
#if defined(__APPLE__)
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);
#endif
  SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

  configDir = platformConfigDir();
  app = std::make_shared<EditorApp>();
  app->init(EDITOR_CSS);
  for (int i = 0; i < app->styleErrorCount(); i++) std::fprintf(stderr, "editor.css: %s\n", app->styleErrorAt(i).c_str());
  app->setPlatform(platformName());
  app->setNow(epochMs());

  window = SDL_CreateWindow("Sliqtly Editor", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, startW, startH,
                            SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
  if (!window) {
    std::fprintf(stderr, "sliqtly-editor: window: %s\n", SDL_GetError());
    return 1;
  }
  SDL_SetWindowMinimumSize(window, 800, 520);
  SDL_GLContext ctx = SDL_GL_CreateContext(window);
  if (!ctx) {
    std::fprintf(stderr, "sliqtly-editor: OpenGL 3.3: %s\n", SDL_GetError());
    return 1;
  }
  SDL_GL_SetSwapInterval(1);
  SDL_StartTextInput();

  Painter painter;
  addFaces(painter);
  std::string err;
  if (!painter.init(err)) {
    std::fprintf(stderr, "sliqtly-editor: %s\n", err.c_str());
    return 1;
  }
  setWindowIcon(paintIcon(painter, 256), 256);
  if (!iconOut.empty()) {
    writePam(iconOut, paintIcon(painter, 1024), 1024, 1024);
    SDL_GL_DeleteContext(ctx);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
  }

  int winW, winH;
  SDL_GetWindowSize(window, &winW, &winH);
  app->setViewport(winW, winH);
  app->loadSettings(platformReadFile(settingsPath()));
  app->start();
  if (!scriptFile.empty()) app->runScript(platformReadFile(scriptFile));

  Workers workers(4);
  OAuthLoopback signIn;
  SDL_Cursor* arrow = SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_ARROW);
  SDL_Cursor* hand = SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_HAND);
  SDL_Cursor* ibeam = SDL_CreateSystemCursor(SDL_SYSTEM_CURSOR_IBEAM);
  std::string cursorNow;

  evg::gl::Target uiTarget, slideTarget, slideFlat;
  EJ viewDoc;
  int viewGen = -1, shownGen = -1, shownSlide = -1;
  double deckW = 1920, deckH = 1080;
  bool force = true;
  std::string pendingShot, title, lastState;
  auto t0 = std::chrono::steady_clock::now();
  long frames = 0;
  double wheelAcc = 0;
  bool leftDown = false;
  const bool mac = std::strcmp(platformName(), "mac") == 0;

  while (!quit) {
    bool busy = workers.pending() > 0 || app->busy() || app->scriptRunning() || signIn.active() || !pendingShot.empty();
    SDL_Event ev;
    bool got = SDL_WaitEventTimeout(&ev, busy ? 8 : 100) != 0;
    while (got) {
      SDL_Keymod km = SDL_GetModState();
      bool mod = mac ? (km & KMOD_GUI) != 0 : (km & KMOD_CTRL) != 0;
      switch (ev.type) {
        case SDL_QUIT: quit = true; break;
        case SDL_WINDOWEVENT:
          if (ev.window.event == SDL_WINDOWEVENT_SIZE_CHANGED || ev.window.event == SDL_WINDOWEVENT_RESIZED) {
            SDL_GetWindowSize(window, &winW, &winH);
            app->setViewport(winW, winH);
          }
          force = true;
          break;
        case SDL_MOUSEMOTION: {
          app->pointerMove(ev.motion.x, ev.motion.y, (ev.motion.state & SDL_BUTTON_LMASK) != 0);
          std::string c = app->cursorAt(ev.motion.x, ev.motion.y);
          if (c != cursorNow) {
            cursorNow = c;
            SDL_SetCursor(c == "text" ? ibeam : c == "pointer" ? hand : arrow);
          }
          break;
        }
        case SDL_MOUSEBUTTONDOWN:
          if (ev.button.button == SDL_BUTTON_LEFT) {
            leftDown = true;
            app->setNow(epochMs());
            app->pointerDown(ev.button.x, ev.button.y, (km & KMOD_SHIFT) != 0);
          }
          break;
        case SDL_MOUSEBUTTONUP:
          if (ev.button.button == SDL_BUTTON_LEFT) {
            leftDown = false;
            app->pointerUp(ev.button.x, ev.button.y);
          }
          break;
        case SDL_MOUSEWHEEL: {
#if SDL_VERSION_ATLEAST(2, 0, 18)
          double dy = ev.wheel.preciseY;
#else
          double dy = ev.wheel.y;
#endif
          if (ev.wheel.direction == SDL_MOUSEWHEEL_FLIPPED) dy = -dy;
          wheelAcc -= dy;
          int lines = (int)wheelAcc;
          if (lines != 0) {
            wheelAcc -= lines;
            int mx, my;
            SDL_GetMouseState(&mx, &my);
            app->wheel(mx, my, lines);
          }
          break;
        }
        case SDL_TEXTINPUT:
          // Cmd / Ctrl + a letter is a shortcut, not text.
          if (!mod) app->typeText(ev.text.text);
          break;
        case SDL_KEYDOWN: {
          SDL_Keycode k = ev.key.keysym.sym;
          const char* name = keyName(k);
          std::string letter;
          if (k >= SDLK_a && k <= SDLK_z) letter = std::string(1, (char)('a' + (k - SDLK_a)));
          if (name) {
            app->key(name, (km & KMOD_SHIFT) != 0, mod, (km & KMOD_ALT) != 0);
          } else if (mod && !letter.empty()) {
            if (letter == "q" && mac) quit = true;
            else app->key(letter, (km & KMOD_SHIFT) != 0, mod, (km & KMOD_ALT) != 0);
          }
          break;
        }
        default: break;
      }
      got = SDL_PollEvent(&ev) != 0;
    }
    (void)leftDown;

    app->setNow(epochMs());
    app->scriptTick();

    // the network
    for (int id = app->takeRequest(); id != 0; id = app->takeRequest()) startRequest(workers, id);
    {
      std::deque<Done> ready;
      std::deque<std::function<void()>> calls;
      {
        std::lock_guard<std::mutex> g(doneLock);
        ready.swap(done);
        calls.swap(mainQueue);
      }
      for (auto& d : ready) app->deliver(d.id, (int)d.status, d.body, d.error);
      for (auto& c : calls) c();
    }
    OAuthLoopback::Result sr;
    if (signIn.take(sr)) {
      if (sr.ok) app->oauthCode(sr.code, signIn.verifier, signIn.redirect);
      else app->oauthFailed(sr.error);
    }

    // what the app asks for
    for (std::string cmd = app->takeCommand(); !cmd.empty(); cmd = app->takeCommand()) {
      std::string arg = app->commandArg();
      if (cmd == "save-settings") {
        if (!platformWritePrivate(settingsPath(), app->settingsJson())) std::fprintf(stderr, "sliqtly-editor: cannot write %s\n", settingsPath().c_str());
      } else if (cmd == "copy") {
        SDL_SetClipboardText(arg.c_str());
      } else if (cmd == "paste") {
        if (char* t = SDL_GetClipboardText()) {
          app->paste(t);
          SDL_free(t);
        }
      } else if (cmd == "open-url") {
        platformOpenUrl(arg);
      } else if (cmd == "oauth") {
        std::string why;
        if (signIn.start(why)) signIn.open(app->oauthAuthorizeUrl(signIn.challenge, signIn.state, signIn.redirect));
        else app->oauthFailed(why);
      } else if (cmd == "fetch-ca") {
        pinCa(workers, arg, app->commandArg2());
      } else if (cmd == "shot") {
        pendingShot = arg;
        force = true;
      } else if (cmd == "log") {
        std::printf("%s\n", arg.c_str());
        std::fflush(stdout);
      } else if (cmd == "fail") {
        std::fprintf(stderr, "script failed: %s\n", arg.c_str());
        scriptFailed = true;
        quit = true;
      } else if (cmd == "quit") {
        quit = true;
      }
    }
    if (debugOn()) {
      std::string st = app->debugState();
      if (st != lastState) {
        std::fprintf(stderr, "state: %s\n", st.c_str());
        lastState = st;
      }
    }
    std::string t = app->windowTitle();
    if (t != title) {
      title = t;
      SDL_SetWindowTitle(window, t.c_str());
    }

    // the preview's slides, when new ones came
    if (app->viewGeneration() != viewGen) {
      viewGen = app->viewGeneration();
      viewDoc = EJ();
      std::string body = app->viewBody();
      if (!body.empty() && evg::json::Parser(body).parse(viewDoc)) {
        if (const EJ* d = viewDoc.get("deck")) {
          deckW = d->numOr("width", 1920);
          deckH = d->numOr("height", 1080);
        }
      }
    }

    double secs = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    bool last = maxSeconds >= 0 && secs >= maxSeconds && frames > 2;
    bool paint = force || app->needsPaint() || shownGen != viewGen || shownSlide != app->previewSlide() || last;
    if (paint) {
      force = false;
      shownGen = viewGen;
      shownSlide = app->previewSlide();
      EJ list;
      if (!evg::json::Parser(app->displayListJson()).parse(list)) {
        std::fprintf(stderr, "sliqtly-editor: the display list did not parse\n");
        return 1;
      }
      int drawW, drawH;
      SDL_GL_GetDrawableSize(window, &drawW, &drawH);
      SDL_GetWindowSize(window, &winW, &winH);
      uiTarget.ensure(drawW, drawH, 4);
      uiTarget.bind();
      painter.draw(list, {winW, winH, drawW, drawH, (float)secs, nullptr});
      uiTarget.resolve(0);
      // The slide: drawn at the preview's size in its own target, then put in place.
      const EJ* lists = viewDoc.get("lists");
      int slide = app->previewSlide();
      if (app->previewVisible() && lists && slide >= 0 && slide < (int)lists->arr.size()) {
        double sx = (double)drawW / winW, sy = (double)drawH / winH;
        int px = (int)std::lround(app->previewX() * sx), py = (int)std::lround(app->previewY() * sy);
        int pw = (int)std::lround(app->previewW() * sx), ph = (int)std::lround(app->previewH() * sy);
        if (pw > 4 && ph > 4) {
          slideTarget.ensure(pw, ph, 4);
          slideTarget.bind();
          painter.draw(lists->arr[slide], {(int)std::lround(deckW), (int)std::lround(deckH), pw, ph, (float)secs, nullptr});
          slideFlat.ensure(pw, ph, 0);
          slideTarget.resolve(slideFlat.fbo());
          glBindFramebuffer(GL_READ_FRAMEBUFFER, slideFlat.fbo());
          glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
          glBlitFramebuffer(0, 0, pw, ph, px, drawH - (py + ph), px + pw, drawH - py, GL_COLOR_BUFFER_BIT, GL_NEAREST);
          glBindFramebuffer(GL_FRAMEBUFFER, 0);
        }
      }
      if (!pendingShot.empty()) {
        shotWindow(pendingShot, drawW, drawH);
        if (debugOn()) std::fprintf(stderr, "shot: %s (%dx%d)\n", pendingShot.c_str(), drawW, drawH);
        pendingShot.clear();
      }
      if (last && !shotAtEnd.empty()) shotWindow(shotAtEnd, drawW, drawH);
      SDL_GL_SwapWindow(window);
      frames++;
    }
    if (last) break;
  }

  SDL_GL_DeleteContext(ctx);
  SDL_DestroyWindow(window);
  SDL_Quit();
  return scriptFailed ? 3 : 0;
}
