import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args:["--use-angle=swiftshader","--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 1400, height: 860 } });
p.on("pageerror", e => console.log("PAGEERR", e.message, (e.stack||"").split("\n").slice(0,4).join(" | ")));
await p.goto("http://localhost:8770/");
await p.waitForFunction(() => window.__app, null, {timeout: 30000});
await p.waitForTimeout(1500);
const src = "# D\n\n## Ominaisuudet\n\n```vega-lite\n{\n  \"data\": {\"values\": [\n    {\"feature\": \"Otsikot\", \"use\": 90},\n    {\"feature\": \"Listat\", \"use\": 75},\n    {\"feature\": \"Kuvat\", \"use\": 40},\n    {\"feature\": \"Kaaviot\", \"use\": 25}\n  ]},\n  \"width\": 640,\n  \"height\": 250,\n  \"mark\": \"bar\",\n  \"encoding\": {\n    \"x\": {\"field\": \"feature\", \"type\": \"nominal\", \"sort\": null, \"title\": null},\n    \"y\": {\"field\": \"use\", \"type\": \"quantitative\", \"title\": \"% of slides\"}\n  }\n}\n```\n";
await p.evaluate((src) => { const a = window.__app; a.setSource(src); a.openChartEditor(5); }, src);
await p.waitForTimeout(800);
await p.mouse.click(57, 245);          // Viiva
await p.waitForTimeout(400);
const cb = await p.locator("#c").boundingBox();
const pos = await p.evaluate(() => { const c = window.__app.chart; const r = c.inputs[4].rootEl; return [c.x + r.calculatedX + 20, c.y + r.calculatedY + 10]; });
console.log("canvas", cb.x, cb.y, "cell at", pos);
await p.mouse.click(cb.x + pos[0], cb.y + pos[1]);
await p.waitForTimeout(200);
console.log("after click", await p.evaluate(() => [window.__app.chart.focusTid, window.__app.focusTarget(), document.activeElement && document.activeElement.id]));
await p.keyboard.press("Backspace"); await p.keyboard.press("Backspace");
await p.keyboard.type("60");
await p.keyboard.press("Tab");
await p.keyboard.type("x");
await p.waitForTimeout(600);
await p.screenshot({ path: process.argv[2] + "/ce2.png" });
console.log(await p.evaluate(() => window.__app.source().split("\n").filter(l => l.includes("Otsikot")).join(" ")));
console.log("valmis", await p.evaluate(() => { const c = window.__app.chart; const f = (id) => { const walk = (e) => { if (e.id === id) return e; for (const k of e.children || []) { const r = walk(k); if (r) return r; } return null; }; return walk(c.host.lastPage); }; const e = f("ce-done"); return [c.x + e.calculatedX, c.y + e.calculatedY, e.calculatedWidth, e.calculatedHeight]; }));
await p.mouse.click(500, 121);        // Valmis
await p.waitForTimeout(300);
console.log("open after Valmis:", await p.evaluate(() => window.__app.chartIsOpen()));
await b.close();
