import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args:["--use-angle=swiftshader","--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 1400, height: 860 } });
p.on("pageerror", e => console.log("PAGEERR", e.message, (e.stack||"").split("\n").slice(0,4).join(" | ")));
await p.goto("http://localhost:8770/");
await p.waitForFunction(() => window.__app, null, {timeout: 30000});
await p.waitForTimeout(1500);
const src = "# D\n\n## Ominaisuudet\n\n```vega-lite\n{\"data\": {\"values\": [{\"f\": \"Otsikot\", \"u\": 90}, {\"f\": \"Listat\", \"u\": 75}, {\"f\": \"Kuvat\", \"u\": 40}]}, \"mark\": \"bar\", \"encoding\": {\"x\": {\"field\": \"f\", \"type\": \"nominal\"}, \"y\": {\"field\": \"u\", \"type\": \"quantitative\"}}}\n```\n";
await p.evaluate((src) => { const a = window.__app; a.setSource(src); a.openChartEditor(5); }, src);
await p.waitForTimeout(1000);
await p.screenshot({ path: process.argv[2] + "/ce5.png" });
const cb = await p.locator("#c").boundingBox();
const bar = await p.evaluate(() => { const c = window.__app.chart; const f = c.win.barEl; return [f.calculatedX + 60, f.calculatedY + 12]; });
await p.mouse.move(cb.x + bar[0], cb.y + bar[1]);
await p.mouse.down();
await p.mouse.move(cb.x + bar[0] + 200, cb.y + bar[1] + 40, { steps: 5 });
await p.mouse.up();
await p.waitForTimeout(600);
console.log("moved to", await p.evaluate(() => [window.__app.chart.x, window.__app.chart.y]));
await p.screenshot({ path: process.argv[2] + "/ce6.png" });
await p.mouse.click(cb.x + 1300, cb.y + 700);
await p.waitForTimeout(300);
console.log("open after outside click:", await p.evaluate(() => window.__app.chartIsOpen()));
await b.close();
