#!/usr/bin/env node
// rgr/*.rgr → sliqtly_mcp.go, with Ranger's own compiler (go generate runs
// this). Ranger is the checkout the editor builds with (npm run setup), or
// RANGER_DIR; rgr/ is linked into it as gallery/sliqtly-mcp, since the
// sources import Ranger's gallery/mfiles JSON by a path relative to it.
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { ensureRanger, ensureRangerDiff, log } from "../scripts/lib.mjs";
import { formatCss } from "../scripts/format-css.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const ranger = ensureRanger();
const at = path.join(ranger, "gallery", "sliqtly-mcp");
try { fs.unlinkSync(at); } catch {}
fs.symlinkSync(path.join(here, "rgr"), at, process.platform === "win32" ? "junction" : "dir");
// RangerDiff's line diff and diff3 (rgr/Work.rgr merges two assistants'
// edits with it), linked in as gallery/rangerdiff
const diffAt = path.join(ranger, "gallery", "rangerdiff");
try { fs.unlinkSync(diffAt); } catch {}
fs.symlinkSync(ensureRangerDiff(), diffAt, process.platform === "win32" ? "junction" : "dir");

const outDir = path.join(ranger, "gallery", "sliqtly-mcp-build");
fs.rmSync(outDir, { recursive: true, force: true });
// the deck model makes this compile need more than node's default heap
const r = spawnSync(process.execPath, ["--max-old-space-size=6144", "dist/rgrc.js", "-l=go", "./gallery/sliqtly-mcp/App.rgr", "-d=./gallery/sliqtly-mcp-build", "-o=sliqtly_mcp.go", "-nodecli"], {
  cwd: ranger, encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
});
const text = `${r.stdout || ""}${r.stderr || ""}`;
const built = path.join(outDir, "sliqtly_mcp.go");
if (r.status !== 0 || /Compilation FAILED/.test(text) || !fs.existsSync(built)) {
  log(text.split("\n").slice(-40).join("\n"));
  process.exit(1);
}
const head = "// Code generated by Ranger from rgr/*.rgr (node gen.mjs). DO NOT EDIT.\n\n";
fs.writeFileSync(path.join(here, "sliqtly_mcp.go"), head + fs.readFileSync(built, "utf8"));
log("wrote  mcp-go/sliqtly_mcp.go");

// The editor's workbook reader (rgr/PresDataGo.rgr → src/PresData.rgr) as a
// package of its own: datagrid's XmlLite and the deck model's XmlCore both
// define XmlAttr, so the two cannot share one compile.
const pdDir = path.join(ranger, "gallery", "sliqtly-mcp-presdata");
fs.rmSync(pdDir, { recursive: true, force: true });
const p = spawnSync(process.execPath, ["dist/rgrc.js", "-l=go", "./gallery/sliqtly-mcp/PresDataGo.rgr", `-d=${pdDir}`, "-o=presdata.go", "-nodecli"], {
  cwd: ranger, encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
});
const pdText = `${p.stdout || ""}${p.stderr || ""}`;
const pdBuilt = path.join(pdDir, "presdata.go");
if (p.status !== 0 || /Compilation FAILED/.test(pdText) || !fs.existsSync(pdBuilt)) {
  log(pdText.split("\n").slice(-40).join("\n"));
  process.exit(1);
}
fs.mkdirSync(path.join(here, "presdata"), { recursive: true });
const pdHead = "// Code generated by Ranger from src/PresData.rgr (node gen.mjs). DO NOT EDIT.\n\n";
fs.writeFileSync(path.join(here, "presdata", "presdata.go"), pdHead + fs.readFileSync(pdBuilt, "utf8").replace(/^package main\b/m, "package presdata"));
log("wrote  mcp-go/presdata/presdata.go");

// RangerDiff's deltas (RdSmart: byte, ZIP-part and PNG deltas) as the Go
// package rdiff, for blobs kept as a delta against another blob
// (store/sqliteblobs.go, store/backup.go). It is compiled from the
// RangerDiff checkout, which names its Ranger packages (core, zip) in its
// own ranger.json; `rgrc install` fetches them. rdsmart.go is committed
// (unlike the other generated files), so a checkout that was built before
// still builds after a pull without running go generate first.
const rd = ensureRangerDiff();
const inst = spawnSync(process.execPath, [path.join(ranger, "dist", "rgrc.js"), "install"], { cwd: rd, encoding: "utf8" });
if (inst.status !== 0) {
  log(`${inst.stdout || ""}${inst.stderr || ""}`);
  process.exit(1);
}
const rdSrc = path.join(here, ".rdiff-build");
fs.mkdirSync(rdSrc, { recursive: true });
const rdImport = path.relative(rdSrc, path.join(rd, "src", "RdSmart.rgr")).split(path.sep).join("/");
fs.writeFileSync(path.join(rdSrc, "RdGo.rgr"), `Import "${rdImport}"\n`);
const rdOut = path.join(rdSrc, "out");
fs.rmSync(rdOut, { recursive: true, force: true });
const rdr = spawnSync(process.execPath, [path.join(ranger, "dist", "rgrc.js"), "-l=go", path.join(rdSrc, "RdGo.rgr"), `-d=${rdOut}`, "-o=rdsmart.go", "-nodecli"], {
  cwd: rd, encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
});
const rdText = `${rdr.stdout || ""}${rdr.stderr || ""}`;
const rdBuilt = path.join(rdOut, "rdsmart.go");
if (rdr.status !== 0 || /Compilation FAILED|\[FAIL\]/.test(rdText) || !fs.existsSync(rdBuilt)) {
  log(rdText.split("\n").slice(-40).join("\n"));
  process.exit(1);
}
const rdHead = "// Code generated by Ranger from RangerDiff src/RdSmart.rgr (node gen.mjs). DO NOT EDIT.\n\n";
fs.mkdirSync(path.join(here, "rdiff"), { recursive: true });
fs.writeFileSync(path.join(here, "rdiff", "rdsmart.go"), rdHead + fs.readFileSync(rdBuilt, "utf8").replace(/^package main\b/m, "package rdiff"));
log("wrote  mcp-go/rdiff/rdsmart.go");

// The faces the editor lays slides out with (web/main.js FACES and its emoji
// face), from the same Ranger checkout scripts/build.mjs copies them from:
// the layout measures with them (host_font) and render.go draws with them.
const fontsDir = path.join(here, "fonts");
fs.mkdirSync(fontsDir, { recursive: true });
for (const [dir, face] of [
  ["Open_Sans", "OpenSans-Regular"], ["Open_Sans", "OpenSans-Bold"], ["Open_Sans", "OpenSans-Italic"], ["Open_Sans", "OpenSans-BoldItalic"],
  ["Noto_Sans", "NotoSans-Regular"], ["Noto_Sans", "NotoSans-Bold"], ["Noto_Sans", "NotoSans-Italic"], ["Noto_Sans", "NotoSans-BoldItalic"],
  ["Noto_Emoji", "NotoEmoji-Regular"],
  ["Gloria_Hallelujah", "GloriaHallelujah"], ["Fjalla_One", "FjallaOne-Regular"], ["Josefin_Sans", "JosefinSans-Bold"], ["Droid_Serif", "DroidSerif-BoldItalic"],
  // the faces a deck's CSS can name (src/PresFonts.rgr)
  ["Droid_Serif", "DroidSerif"], ["Droid_Serif", "DroidSerif-Bold"], ["Droid_Serif", "DroidSerif-Italic"],
]) {
  fs.copyFileSync(path.join(ranger, "gallery/pdf_writer/assets/fonts", dir, `${face}.ttf`), path.join(fontsDir, `${face}.ttf`));
}
// Lato is kept in this repository (fonts/Lato, OFL)
for (const face of ["Lato-Regular", "Lato-Bold", "Lato-Italic", "Lato-BoldItalic"]) {
  fs.copyFileSync(path.join(here, "..", "fonts", "Lato", `${face}.ttf`), path.join(fontsDir, `${face}.ttf`));
}
log("copied mcp-go/fonts/*.ttf");

// The themes' sheets, built into every server (host.go Theme): the public
// site no longer serves /themes/, and a server that keeps decks in a
// folder (SLIQTLY_DATA) has no site at all.
const themesDir = path.join(here, "themes");
fs.rmSync(themesDir, { recursive: true, force: true });
fs.mkdirSync(themesDir, { recursive: true });
for (const f of fs.readdirSync(path.join(here, "..", "themes"))) {
  if (f.endsWith(".css")) fs.copyFileSync(path.join(here, "..", "themes", f), path.join(themesDir, f));
}
// editorial comes from Ranger, as the editor's build takes
// it (scripts/build.mjs): every theme is built in, so the server never
// needs the site to lay a deck out
for (const t of ["editorial"]) {
  fs.writeFileSync(path.join(themesDir, `${t}.css`), formatCss(fs.readFileSync(path.join(ranger, `gallery/markdown/fixtures/themes/${t}.css`), "utf8")));
}
log("copied mcp-go/themes/*.css");

// The editor and player (web/dist, npm run build), built into the binary so
// a server of one's own serves them (localweb.go). Without a build the
// server shows its decks as pictures only. SLIQTLY_BUILD_WEB=viewer builds
// in the public viewer instead (web/dist-view, npm run build:view): the
// server plays presentations and has no editor (the .deb's default).
const viewer = process.env.SLIQTLY_BUILD_WEB === "viewer";
const webDist = path.join(here, "..", "web", viewer ? "dist-view" : "dist");
const webOut = path.join(here, "webdist");
fs.mkdirSync(webOut, { recursive: true });
for (const f of fs.readdirSync(webOut)) if (f !== "README") fs.rmSync(path.join(webOut, f), { recursive: true, force: true });
if (fs.existsSync(path.join(webDist, "index.html"))) {
  // fonts/ is left out: the server serves the page's faces from its own
  // copy (fonts.go, the same files)
  fs.cpSync(webDist, webOut, { recursive: true, filter: (src) => path.relative(webDist, src).split(path.sep)[0] !== "fonts" });
  log(`copied web/${viewer ? "dist-view" : "dist"} → mcp-go/webdist`);
} else if (viewer) {
  throw new Error("no web/dist-view (npm run build:view) for SLIQTLY_BUILD_WEB=viewer");
} else {
  log("no web/dist (npm run build): the binary will have no editor");
}
