#!/usr/bin/env node
// rgr/*.rgr → sliqtly_mcp.go, with Ranger's own compiler (go generate runs
// this). Ranger is the checkout the editor builds with (npm run setup), or
// RANGER_DIR; rgr/ is linked into it as gallery/sliqtly-mcp, since the
// sources import Ranger's gallery/mfiles JSON by a path relative to it.
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { ensureRanger, ensureRangerDiff, log } from "../scripts/lib.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const ranger = ensureRanger();
const at = path.join(ranger, "gallery", "sliqtly-mcp");
try { fs.unlinkSync(at); } catch {}
fs.symlinkSync(path.join(here, "rgr"), at, process.platform === "win32" ? "junction" : "dir");
// RangerDiff's line diff and diff3 (rgr/Work.rgr merges two assistants'
// edits with it), linked in as gallery/rangerdiff
const diffAt = path.join(ranger, "gallery", "rangerdiff");
try { fs.unlinkSync(diffAt); } catch {}
fs.symlinkSync(ensureRangerDiff(), diffAt, process.platform === "win32" ? "junction" : "dir");

const outDir = path.join(ranger, "gallery", "sliqtly-mcp-build");
fs.rmSync(outDir, { recursive: true, force: true });
// the deck model makes this compile need more than node's default heap
const r = spawnSync(process.execPath, ["--max-old-space-size=6144", "dist/rgrc.js", "-l=go", "./gallery/sliqtly-mcp/App.rgr", "-d=./gallery/sliqtly-mcp-build", "-o=sliqtly_mcp.go", "-nodecli"], {
  cwd: ranger, encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
});
const text = `${r.stdout || ""}${r.stderr || ""}`;
const built = path.join(outDir, "sliqtly_mcp.go");
if (r.status !== 0 || /Compilation FAILED/.test(text) || !fs.existsSync(built)) {
  log(text.split("\n").slice(-40).join("\n"));
  process.exit(1);
}
const head = "// Code generated by Ranger from rgr/*.rgr (node gen.mjs). DO NOT EDIT.\n\n";
fs.writeFileSync(path.join(here, "sliqtly_mcp.go"), head + fs.readFileSync(built, "utf8"));
log("wrote  mcp-go/sliqtly_mcp.go");

// The editor's workbook reader (rgr/PresDataGo.rgr → src/PresData.rgr) as a
// package of its own: datagrid's XmlLite and the deck model's XmlCore both
// define XmlAttr, so the two cannot share one compile.
const pdDir = path.join(ranger, "gallery", "sliqtly-mcp-presdata");
fs.rmSync(pdDir, { recursive: true, force: true });
const p = spawnSync(process.execPath, ["dist/rgrc.js", "-l=go", "./gallery/sliqtly-mcp/PresDataGo.rgr", `-d=${pdDir}`, "-o=presdata.go", "-nodecli"], {
  cwd: ranger, encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
});
const pdText = `${p.stdout || ""}${p.stderr || ""}`;
const pdBuilt = path.join(pdDir, "presdata.go");
if (p.status !== 0 || /Compilation FAILED/.test(pdText) || !fs.existsSync(pdBuilt)) {
  log(pdText.split("\n").slice(-40).join("\n"));
  process.exit(1);
}
fs.mkdirSync(path.join(here, "presdata"), { recursive: true });
const pdHead = "// Code generated by Ranger from src/PresData.rgr (node gen.mjs). DO NOT EDIT.\n\n";
fs.writeFileSync(path.join(here, "presdata", "presdata.go"), pdHead + fs.readFileSync(pdBuilt, "utf8").replace(/^package main\b/m, "package presdata"));
log("wrote  mcp-go/presdata/presdata.go");

// The faces the editor lays slides out with (web/main.js FACES and its emoji
// face), from the same Ranger checkout scripts/build.mjs copies them from:
// the layout measures with them (host_font) and render.go draws with them.
const fontsDir = path.join(here, "fonts");
fs.mkdirSync(fontsDir, { recursive: true });
for (const [dir, face] of [
  ["Open_Sans", "OpenSans-Regular"], ["Open_Sans", "OpenSans-Bold"], ["Open_Sans", "OpenSans-Italic"], ["Open_Sans", "OpenSans-BoldItalic"],
  ["Noto_Sans", "NotoSans-Regular"], ["Noto_Sans", "NotoSans-Bold"], ["Noto_Sans", "NotoSans-Italic"], ["Noto_Sans", "NotoSans-BoldItalic"],
  ["Noto_Emoji", "NotoEmoji-Regular"],
]) {
  fs.copyFileSync(path.join(ranger, "gallery/pdf_writer/assets/fonts", dir, `${face}.ttf`), path.join(fontsDir, `${face}.ttf`));
}
log("copied mcp-go/fonts/*.ttf");

// The themes' sheets, for a server that keeps decks in a folder
// (SLIQTLY_DATA): it has no site to fetch /themes/{name}.css from.
const themesDir = path.join(here, "themes");
fs.rmSync(themesDir, { recursive: true, force: true });
fs.mkdirSync(themesDir, { recursive: true });
for (const f of fs.readdirSync(path.join(here, "..", "themes"))) {
  if (f.endsWith(".css")) fs.copyFileSync(path.join(here, "..", "themes", f), path.join(themesDir, f));
}
log("copied mcp-go/themes/*.css");

// The editor and player (web/dist, npm run build), built into the binary so
// a server of one's own serves them (localweb.go). Without a build the
// server shows its decks as pictures only.
const webDist = path.join(here, "..", "web", "dist");
const webOut = path.join(here, "webdist");
fs.mkdirSync(webOut, { recursive: true });
for (const f of fs.readdirSync(webOut)) if (f !== "README") fs.rmSync(path.join(webOut, f), { recursive: true, force: true });
if (fs.existsSync(path.join(webDist, "index.html"))) {
  // fonts/ is left out: the server serves the page's faces from its own
  // copy (fonts.go, the same files)
  fs.cpSync(webDist, webOut, { recursive: true, filter: (src) => path.relative(webDist, src).split(path.sep)[0] !== "fonts" });
  log("copied web/dist → mcp-go/webdist");
} else {
  log("no web/dist (npm run build): the binary will have no editor");
}
