#!/usr/bin/env node
// rgr/*.rgr → sliqtly_mcp.go, with Ranger's own compiler (go generate runs
// this). Ranger is the checkout the editor builds with (npm run setup), or
// RANGER_DIR; rgr/ is linked into it as gallery/sliqtly-mcp, since the
// sources import Ranger's gallery/mfiles JSON by a path relative to it.
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { ensureRanger, log } from "../scripts/lib.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const ranger = ensureRanger();
const at = path.join(ranger, "gallery", "sliqtly-mcp");
try { fs.unlinkSync(at); } catch {}
fs.symlinkSync(path.join(here, "rgr"), at, process.platform === "win32" ? "junction" : "dir");

const outDir = path.join(ranger, "gallery", "sliqtly-mcp-build");
fs.rmSync(outDir, { recursive: true, force: true });
// the deck model makes this compile need more than node's default heap
const r = spawnSync(process.execPath, ["--max-old-space-size=6144", "dist/rgrc.js", "-l=go", "./gallery/sliqtly-mcp/App.rgr", "-d=./gallery/sliqtly-mcp-build", "-o=sliqtly_mcp.go", "-nodecli"], {
  cwd: ranger, encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
});
const text = `${r.stdout || ""}${r.stderr || ""}`;
const built = path.join(outDir, "sliqtly_mcp.go");
if (r.status !== 0 || /Compilation FAILED/.test(text) || !fs.existsSync(built)) {
  log(text.split("\n").slice(-40).join("\n"));
  process.exit(1);
}
const head = "// Code generated by Ranger from rgr/*.rgr (node gen.mjs). DO NOT EDIT.\n\n";
fs.writeFileSync(path.join(here, "sliqtly_mcp.go"), head + fs.readFileSync(built, "utf8"));
log("wrote  mcp-go/sliqtly_mcp.go");
