// Code generated by Ranger from rgr/*.rgr (node gen.mjs). DO NOT EDIT.

package main
import (
  "math"
  "strconv"
  "strings"
  "net/http"
)

type GoNullable struct {
  value interface{}
  has_value bool
}


func r_div_f64(a float64, b float64) float64 {
    return a / b
}


func r_str_2_i64(s string) *GoNullable {
   res := new(GoNullable);
   if v, err := strconv.ParseInt(s, 10, 64); err == nil {
     res.has_value = true
     res.value = v
   } else {
     res.has_value = false
   }
   return res
}

func r_str_2_d64(s string) *GoNullable {
   res := new(GoNullable);
   if v, err := strconv.ParseFloat(s, 64); err == nil {
     res.has_value = true
     res.value = v
   } else {
     res.has_value = false
   }
   return res
}
type MfJ struct { 
  kind int64 `json:"kind"` 
  flag bool `json:"flag"` 
  num float64 `json:"num"` 
  str string `json:"str"` 
  arr []*MfJ `json:"arr"` 
  ks []string `json:"ks"` 
  vs []*MfJ `json:"vs"` 
}

func CreateNew_MfJ() *MfJ {
  me := new(MfJ)
  me.kind = int64(0)
  me.flag = false
  me.num = 0.0
  me.str = ""
  me.arr = make([]*MfJ,0)
  me.ks = make([]string,0)
  me.vs = make([]*MfJ,0)
  return me;
}
func MfJ_static_nul() *MfJ {
  return CreateNew_MfJ()
}
func MfJ_static_ofBool(b bool) *MfJ {
  var j *MfJ= CreateNew_MfJ();
  j.kind = int64(1); 
  j.flag = b; 
  return j
}
func MfJ_static_ofNum(n float64) *MfJ {
  var j *MfJ= CreateNew_MfJ();
  j.kind = int64(2); 
  j.num = n; 
  return j
}
func MfJ_static_ofInt(n int64) *MfJ {
  var j *MfJ= CreateNew_MfJ();
  j.kind = int64(2); 
  j.num = float64( n ); 
  return j
}
func MfJ_static_ofStr(s string) *MfJ {
  var j *MfJ= CreateNew_MfJ();
  j.kind = int64(3); 
  j.str = s; 
  return j
}
func MfJ_static_newArr() *MfJ {
  var j *MfJ= CreateNew_MfJ();
  j.kind = int64(4); 
  return j
}
func MfJ_static_newObj() *MfJ {
  var j *MfJ= CreateNew_MfJ();
  j.kind = int64(5); 
  return j
}
func MfJ_static_numText(n float64) string {
  if  n != n {
    return "null"
  }
  var whole int64= int64(math.Floor(n));
  var back float64= float64( whole );
  if  back == n {
    return strconv.FormatInt(whole, 10)
  }
  return strconv.FormatFloat(n,'f', -1, 64)
}
func MfJ_static_quote(s string) string {
  var parts []string = make([]string, 0);
  parts = append(parts,"\""); 
  var n int64= int64(len(s));
  var start int64= int64(0);
  var i int64= int64(0);
  for i < n {
    var c int64= int64(s[i]);
    var esc string= "";
    if  c == int64(34) {
      esc = "\\\""; 
    }
    if  c == int64(92) {
      esc = "\\\\"; 
    }
    if  c == int64(10) {
      esc = "\\n"; 
    }
    if  c == int64(13) {
      esc = "\\r"; 
    }
    if  c == int64(9) {
      esc = "\\t"; 
    }
    if  int64(len(esc)) == int64(0) {
      if  c < int64(32) {
        var hex string= "0123456789abcdef";
        var hi int64= int64(math.Floor(r_div_f64(float64(c), float64(int64(16)))));
        var lo int64= c % int64(16);
        esc = ("\\u00" + hex[hi:(hi + int64(1))]) + hex[lo:(lo + int64(1))]; 
      }
    }
    if  int64(len(esc)) > int64(0) {
      if  i > start {
        parts = append(parts,s[start:i]); 
      }
      parts = append(parts,esc); 
      start = i + int64(1); 
    }
    i = i + int64(1); 
  }
  if  n > start {
    parts = append(parts,s[start:n]); 
  }
  parts = append(parts,"\""); 
  return strings.Join(parts, "")
}
func MfJ_static_parse(text string) *MfJ {
  var p *MfJsonReader= CreateNew_MfJsonReader(); _ = p
  return p.read(text)
}
func (this *MfJ) isNull () bool {
  return this.kind == int64(0)
}
func (this *MfJ) isObj () bool {
  return this.kind == int64(5)
}
func (this *MfJ) isArr () bool {
  return this.kind == int64(4)
}
func (this *MfJ) has (key string) bool {
  for _, k := range this.ks {
    if  k == key {
      return true
    }
  }
  return false
}
func (this *MfJ) field (key string) *MfJ {
  var n int64= int64(len(this.ks));
  var i int64= int64(0);
  for i < n {
    var k string= this.ks[i];
    if  k == key {
      var v *MfJ= this.vs[i];
      return v
    }
    i = i + int64(1); 
  }
  return CreateNew_MfJ()
}
func (this *MfJ) put (key string, v *MfJ) *MfJ {
  this.kind = int64(5); 
  var n int64= int64(len(this.ks));
  var i int64= int64(0);
  for i < n {
    var k string= this.ks[i];
    if  k == key {
      this.vs[i] = v;
      return this
    }
    i = i + int64(1); 
  }
  this.ks = append(this.ks,key); 
  this.vs = append(this.vs,v); 
  return this
}
func (this *MfJ) putStr (key string, s string) *MfJ {
  var v *MfJ= MfJ_static_ofStr(s);
  return this.put(key, v)
}
func (this *MfJ) putInt (key string, n int64) *MfJ {
  var v *MfJ= MfJ_static_ofInt(n);
  return this.put(key, v)
}
func (this *MfJ) putNum (key string, n float64) *MfJ {
  var v *MfJ= MfJ_static_ofNum(n);
  return this.put(key, v)
}
func (this *MfJ) putBool (key string, b bool) *MfJ {
  var v *MfJ= MfJ_static_ofBool(b);
  return this.put(key, v)
}
func (this *MfJ) str_ (key string) string {
  var v *MfJ= this.field(key); _ = v
  if  v.kind == int64(3) {
    return v.str
  }
  if  v.kind == int64(2) {
    return MfJ_static_numText(v.num)
  }
  return ""
}
func (this *MfJ) int_ (key string, fallback int64) int64 {
  var v *MfJ= this.field(key); _ = v
  if  v.kind == int64(2) {
    return int64(math.Floor(v.num))
  }
  if  v.kind == int64(3) {
    var p *GoNullable = new(GoNullable); 
    var p__src *GoNullable = r_str_2_i64(v.str);
    p.value = p__src.value;
    p.has_value = p__src.has_value;
    if  p.has_value {
      return p.value.(int64)
    }
  }
  return fallback
}
func (this *MfJ) num_ (key string, fallback float64) float64 {
  var v *MfJ= this.field(key); _ = v
  if  v.kind == int64(2) {
    return v.num
  }
  return fallback
}
func (this *MfJ) bool_ (key string, fallback bool) bool {
  var v *MfJ= this.field(key); _ = v
  if  v.kind == int64(1) {
    return v.flag
  }
  return fallback
}
func (this *MfJ) list (key string) []*MfJ {
  var v *MfJ= this.field(key); _ = v
  if  v.kind == int64(4) {
    return v.arr
  }
  var none []*MfJ = make([]*MfJ, 0);
  return none
}
func (this *MfJ) add (v *MfJ) *MfJ {
  this.kind = int64(4); 
  this.arr = append(this.arr,v); 
  return this
}
func (this *MfJ) count () int64 {
  if  this.kind == int64(4) {
    return int64(len(this.arr))
  }
  if  this.kind == int64(5) {
    return int64(len(this.ks))
  }
  return int64(0)
}
func (this *MfJ) item (i int64) *MfJ {
  if  this.kind != int64(4) {
    return CreateNew_MfJ()
  }
  if  i < int64(0) || i >= int64(len(this.arr)) {
    return CreateNew_MfJ()
  }
  var v *MfJ= this.arr[i];
  return v
}
func (this *MfJ) emit (out []string) () {
  if  this.kind == int64(0) {
    out = append(out,"null"); 
    return
  }
  if  this.kind == int64(1) {
    if  this.flag {
      out = append(out,"true"); 
    } else {
      out = append(out,"false"); 
    }
    return
  }
  if  this.kind == int64(2) {
    out = append(out,MfJ_static_numText(this.num)); 
    return
  }
  if  this.kind == int64(3) {
    out = append(out,MfJ_static_quote(this.str)); 
    return
  }
  if  this.kind == int64(4) {
    out = append(out,"["); 
    var n int64= int64(len(this.arr));
    var i int64= int64(0);
    for i < n {
      if  i > int64(0) {
        out = append(out,","); 
      }
      var v *MfJ= this.arr[i]; _ = v
      v.emit(out);
      i = i + int64(1); 
    }
    out = append(out,"]"); 
    return
  }
  out = append(out,"{"); 
  var m int64= int64(len(this.ks));
  var j int64= int64(0);
  for j < m {
    if  j > int64(0) {
      out = append(out,","); 
    }
    var k string= this.ks[j];
    out = append(out,MfJ_static_quote(k)); 
    out = append(out,":"); 
    var fv *MfJ= this.vs[j]; _ = fv
    fv.emit(out);
    j = j + int64(1); 
  }
  out = append(out,"}"); 
}
func (this *MfJ) toJson () string {
  var out []string = make([]string, 0);
  this.emit(out);
  return strings.Join(out, "")
}
type MfJsonReader struct { 
  src string `json:"src"` 
  pos int64 `json:"pos"` 
  __len int64 `json:"len"` 
  error string `json:"error"` 
}

func CreateNew_MfJsonReader() *MfJsonReader {
  me := new(MfJsonReader)
  me.src = ""
  me.pos = int64(0)
  me.__len = int64(0)
  me.error = ""
  return me;
}
func MfJsonReader_static_hexVal(c int64) int64 {
  if  c >= int64(48) && c <= int64(57) {
    return c - int64(48)
  }
  if  c >= int64(97) && c <= int64(102) {
    return c - int64(87)
  }
  if  c >= int64(65) && c <= int64(70) {
    return c - int64(55)
  }
  return int64(0)
}
func (this *MfJsonReader) read (text string) *MfJ {
  this.src = text; 
  this.pos = int64(0); 
  this.__len = int64(len(text)); 
  this.error = ""; 
  var v *MfJ= this.value();
  this.ws();
  if  int64(len(this.error)) == int64(0) {
    if  this.pos < this.__len {
      this.error = "unexpected text at " + strconv.FormatInt(this.pos, 10); 
    }
  }
  return v
}
func (this *MfJsonReader) ws () () {
  var going bool= true;
  for this.pos < this.__len && going {
    var c int64= int64(this.src[this.pos]);
    if  ((c == int64(32) || c == int64(10)) || c == int64(13)) || c == int64(9) {
      this.pos = this.pos + int64(1); 
    } else {
      going = false; 
    }
  }
}
func (this *MfJsonReader) fail (why string) *MfJ {
  if  int64(len(this.error)) == int64(0) {
    this.error = (why + " at ") + strconv.FormatInt(this.pos, 10); 
  }
  this.pos = this.__len; 
  return CreateNew_MfJ()
}
func (this *MfJsonReader) value () *MfJ {
  this.ws();
  if  this.pos >= this.__len {
    return this.fail("unexpected end")
  }
  var c int64= int64(this.src[this.pos]);
  if  c == int64(123) {
    return this.object()
  }
  if  c == int64(91) {
    return this.array()
  }
  if  c == int64(34) {
    var s string= this.stringLit();
    return MfJ_static_ofStr(s)
  }
  if  c == int64(116) {
    return this.word("true", MfJ_static_ofBool(true))
  }
  if  c == int64(102) {
    return this.word("false", MfJ_static_ofBool(false))
  }
  if  c == int64(110) {
    return this.word("null", CreateNew_MfJ())
  }
  return this.number()
}
func (this *MfJsonReader) word (w string, v *MfJ) *MfJ {
  var n int64= int64(len(w));
  if  this.pos + n > this.__len {
    return this.fail("bad literal")
  }
  if  this.src[this.pos:(this.pos + n)] != w {
    return this.fail("bad literal")
  }
  this.pos = this.pos + n; 
  return v
}
func (this *MfJsonReader) number () *MfJ {
  var start int64= this.pos;
  var going bool= true;
  for this.pos < this.__len && going {
    var c int64= int64(this.src[this.pos]);
    var numeric bool= c >= int64(48) && c <= int64(57);
    if  ((c == int64(45) || c == int64(43)) || c == int64(46)) || (c == int64(101) || c == int64(69)) {
      numeric = true; 
    }
    if  numeric {
      this.pos = this.pos + int64(1); 
    } else {
      going = false; 
    }
  }
  if  this.pos == start {
    return this.fail("unexpected character")
  }
  var t string= this.src[start:this.pos];
  var d *GoNullable = new(GoNullable); 
  var d__src *GoNullable = r_str_2_d64(t);
  d.value = d__src.value;
  d.has_value = d__src.has_value;
  if  !d.has_value  {
    return this.fail("bad number")
  }
  return MfJ_static_ofNum(d.value.(float64))
}
func (this *MfJsonReader) stringLit () string {
  this.pos = this.pos + int64(1); 
  var parts []string = make([]string, 0);
  var start int64= this.pos;
  var done bool= false;
  for this.pos < this.__len && done == false {
    var c int64= int64(this.src[this.pos]);
    if  c == int64(34) {
      if  this.pos > start {
        parts = append(parts,this.src[start:this.pos]); 
      }
      this.pos = this.pos + int64(1); 
      done = true; 
    } else {
      if  c == int64(92) {
        if  this.pos > start {
          parts = append(parts,this.src[start:this.pos]); 
        }
        var e int64= int64(0);
        if  this.pos + int64(1) < this.__len {
          e = int64(this.src[(this.pos + int64(1))]); 
        }
        this.pos = this.pos + int64(2); 
        if  e == int64(110) {
          parts = append(parts,"\n"); 
        }
        if  e == int64(116) {
          parts = append(parts,"\t"); 
        }
        if  e == int64(114) {
          parts = append(parts,"\r"); 
        }
        if  e == int64(98) {
          parts = append(parts,string([]rune{rune(int64(8))})); 
        }
        if  e == int64(102) {
          parts = append(parts,string([]rune{rune(int64(12))})); 
        }
        if  (e == int64(34) || e == int64(92)) || e == int64(47) {
          parts = append(parts,string([]rune{rune(e)})); 
        }
        if  e == int64(117) {
          var code int64= int64(0);
          var k int64= int64(0);
          for k < int64(4) && this.pos < this.__len {
            var hc int64= int64(this.src[this.pos]);
            code = code * int64(16) + MfJsonReader_static_hexVal(hc); 
            this.pos = this.pos + int64(1); 
            k = k + int64(1); 
          }
          parts = append(parts,string([]rune{rune(code)})); 
        }
        start = this.pos; 
      } else {
        this.pos = this.pos + int64(1); 
      }
    }
  }
  if  done == false {
    this.fail("unterminated string");
  }
  return strings.Join(parts, "")
}
func (this *MfJsonReader) array () *MfJ {
  this.pos = this.pos + int64(1); 
  var out *MfJ= MfJ_static_newArr();
  this.ws();
  if  this.pos < this.__len {
    if  int64(this.src[this.pos]) == int64(93) {
      this.pos = this.pos + int64(1); 
      return out
    }
  }
  var going bool= true;
  for going {
    var v *MfJ= this.value();
    out.add(v);
    this.ws();
    if  this.pos >= this.__len {
      return this.fail("unterminated array")
    }
    var c int64= int64(this.src[this.pos]);
    this.pos = this.pos + int64(1); 
    if  c == int64(93) {
      going = false; 
    } else {
      if  c != int64(44) {
        return this.fail("expected , or ]")
      }
    }
  }
  return out
}
func (this *MfJsonReader) object () *MfJ {
  this.pos = this.pos + int64(1); 
  var out *MfJ= MfJ_static_newObj();
  this.ws();
  if  this.pos < this.__len {
    if  int64(this.src[this.pos]) == int64(125) {
      this.pos = this.pos + int64(1); 
      return out
    }
  }
  var going bool= true;
  for going {
    this.ws();
    if  this.pos >= this.__len {
      return this.fail("unterminated object")
    }
    if  int64(this.src[this.pos]) != int64(34) {
      return this.fail("expected key")
    }
    var k string= this.stringLit();
    this.ws();
    if  this.pos >= this.__len {
      return this.fail("unterminated object")
    }
    if  int64(this.src[this.pos]) != int64(58) {
      return this.fail("expected :")
    }
    this.pos = this.pos + int64(1); 
    var v *MfJ= this.value();
    out.put(k, v);
    this.ws();
    if  this.pos >= this.__len {
      return this.fail("unterminated object")
    }
    var c int64= int64(this.src[this.pos]);
    this.pos = this.pos + int64(1); 
    if  c == int64(125) {
      going = false; 
    } else {
      if  c != int64(44) {
        return this.fail("expected , or }")
      }
    }
  }
  return out
}
type JOut struct { 
  parts []string `json:"parts"` 
}

func CreateNew_JOut() *JOut {
  me := new(JOut)
  me.parts = make([]string,0)
  return me;
}
func JOut_static_text(v *MfJ) string {
  var w *JOut= CreateNew_JOut();
  w.write(v);
  return strings.Join(w.parts, "")
}
func (this *JOut) write (v *MfJ) () {
  if  v.kind == int64(0) {
    this.parts = append(this.parts,"null"); 
    return
  }
  if  v.kind == int64(1) {
    if  v.flag {
      this.parts = append(this.parts,"true"); 
    } else {
      this.parts = append(this.parts,"false"); 
    }
    return
  }
  if  v.kind == int64(2) {
    this.parts = append(this.parts,MfJ_static_numText(v.num)); 
    return
  }
  if  v.kind == int64(3) {
    this.parts = append(this.parts,MfJ_static_quote(v.str)); 
    return
  }
  if  v.kind == int64(4) {
    this.parts = append(this.parts,"["); 
    var n int64= int64(len(v.arr));
    var i int64= int64(0);
    for i < n {
      if  i > int64(0) {
        this.parts = append(this.parts,","); 
      }
      var item *MfJ= v.arr[i];
      this.write(item);
      i = i + int64(1); 
    }
    this.parts = append(this.parts,"]"); 
    return
  }
  this.parts = append(this.parts,"{"); 
  var m int64= int64(len(v.ks));
  var j int64= int64(0);
  for j < m {
    if  j > int64(0) {
      this.parts = append(this.parts,","); 
    }
    var k string= v.ks[j];
    this.parts = append(this.parts,MfJ_static_quote(k)); 
    this.parts = append(this.parts,":"); 
    var fv *MfJ= v.vs[j];
    this.write(fv);
    j = j + int64(1); 
  }
  this.parts = append(this.parts,"}"); 
}
type J struct { 
}

func CreateNew_J() *J {
  me := new(J)
  return me;
}
func J_static_obj() *MfJ {
  return MfJ_static_newObj()
}
func J_static_arr() *MfJ {
  return MfJ_static_newArr()
}
func J_static_s(v string) *MfJ {
  return MfJ_static_ofStr(v)
}
func J_static_n(v int64) *MfJ {
  return MfJ_static_ofInt(v)
}
func J_static_b(v bool) *MfJ {
  return MfJ_static_ofBool(v)
}
func J_static_nul() *MfJ {
  return CreateNew_MfJ()
}
func J_static_strs(list []string) *MfJ {
  var a *MfJ= MfJ_static_newArr();
  for _, s := range list {
    a.add(MfJ_static_ofStr(s));
  }
  return a
}
func J_static_strList(v *MfJ) []string {
  var out []string = make([]string, 0);
  if  v.kind == int64(4) {
    for _, item := range v.arr {
      if  item.kind == int64(3) {
        out = append(out,item.str); 
      }
    }
  }
  return out
}
func J_static_parse(text string) *MfJ {
  if  int64(len(text)) == int64(0) {
    return CreateNew_MfJ()
  }
  return MfJ_static_parse(text)
}
func J_static_textOf(v *MfJ, key string) string {
  var f *MfJ= v.field(key); _ = f
  if  f.kind == int64(3) {
    return f.str
  }
  if  f.kind == int64(2) {
    return MfJ_static_numText(f.num)
  }
  if  f.kind == int64(1) {
    if  f.flag {
      return "true"
    }
    return "false"
  }
  return ""
}
func J_static_truthy(v *MfJ) bool {
  if  v.kind == int64(0) {
    return false
  }
  if  v.kind == int64(1) {
    return v.flag
  }
  if  v.kind == int64(2) {
    return v.num != 0.0
  }
  if  v.kind == int64(3) {
    return int64(len(v.str)) > int64(0)
  }
  return true
}
type Img struct { 
  name string `json:"name"` 
  _type string `json:"type"` 
  handle int64 `json:"handle"` 
  size int64 `json:"size"` 
}

func CreateNew_Img() *Img {
  me := new(Img)
  me.name = ""
  me._type = ""
  me.handle = int64(0)
  me.size = int64(0)
  return me;
}
type Loaded struct { 
  err string `json:"err"` 
  imgs []*Img `json:"imgs"` 
}

func CreateNew_Loaded() *Loaded {
  me := new(Loaded)
  me.err = ""
  me.imgs = make([]*Img,0)
  return me;
}
type Outline struct { 
  titles []string `json:"titles"` 
  media []string `json:"media"` 
}

func CreateNew_Outline() *Outline {
  me := new(Outline)
  me.titles = make([]string,0)
  me.media = make([]string,0)
  return me;
}
type Deck struct { 
}

func CreateNew_Deck() *Deck {
  me := new(Deck)
  return me;
}
func Deck_static_THEMES() []string {
  return []string {"aurora", "nebula", "carbon", "ember", "midnight", "corporate", "editorial"}
}
func Deck_static_MAX_MD() int64 {
  return int64(307200)
}
func Deck_static_MAX_CSS() int64 {
  return int64(102400)
}
func Deck_static_MAX_IMAGE() int64 {
  return int64(5242880)
}
func Deck_static_MAX_IMAGES() int64 {
  return int64(20)
}
func Deck_static_isSpace(c int64) bool {
  return ((c == int64(32) || c == int64(9)) || (c == int64(10) || c == int64(13))) || (c == int64(11) || c == int64(12))
}
func Deck_static_isAlnum(c int64) bool {
  return (c >= int64(48) && c <= int64(57) || c >= int64(65) && c <= int64(90)) || c >= int64(97) && c <= int64(122)
}
func Deck_static_nameChar(c int64) bool {
  return (Deck_static_isAlnum(c) || c == int64(46)) || (c == int64(95) || c == int64(45))
}
func Deck_static_cleanName(name string) string {
  var t string= strings.TrimSpace(name);
  if  strings.HasPrefix(t, "media/") {
    t = t[int64(6):int64(len(t))]; 
  }
  var parts []string = make([]string, 0);
  var n int64= int64(len(t));
  var i int64= int64(0);
  var inSpace bool= false;
  for i < n {
    var c int64= int64(t[i]);
    if  Deck_static_isSpace(c) {
      if  inSpace == false {
        parts = append(parts,"-"); 
      }
      inSpace = true; 
    } else {
      inSpace = false; 
      if  Deck_static_nameChar(c) {
        parts = append(parts,t[i:(i + int64(1))]); 
      }
    }
    i = i + int64(1); 
  }
  var s string= strings.Join(parts, "");
  if  (int64(len(s)) == int64(0) || strings.HasPrefix(s, ".")) || int64(len(s)) > int64(80) {
    return ""
  }
  var dot int64= int64(strings.LastIndex(s, "."));
  if  dot >= int64(0) {
    var ext string= s[(dot + int64(1)):int64(len(s))];
    if  int64(len(ext)) > int64(0) {
      if  Deck_static_allAlnum(ext) {
        return s[int64(0):(dot + int64(1))] + strings.ToLower(ext)
      }
    }
  }
  return s
}
func Deck_static_allAlnum(s string) bool {
  var n int64= int64(len(s));
  var i int64= int64(0);
  for i < n {
    if  Deck_static_isAlnum(int64(s[i])) == false {
      return false
    }
    i = i + int64(1); 
  }
  return true
}
func Deck_static_typeOf(name string, given string) string {
  if  ((given == "image/png" || given == "image/jpeg") || (given == "image/gif" || given == "image/webp")) || given == "image/svg+xml" {
    return given
  }
  var dot int64= int64(strings.LastIndex(name, "."));
  if  dot < int64(0) {
    return ""
  }
  var ext string= name[(dot + int64(1)):int64(len(name))];
  if  ext == "png" {
    return "image/png"
  }
  if  ext == "jpg" || ext == "jpeg" {
    return "image/jpeg"
  }
  if  ext == "gif" {
    return "image/gif"
  }
  if  ext == "webp" {
    return "image/webp"
  }
  if  ext == "svg" {
    return "image/svg+xml"
  }
  return ""
}
func Deck_static_fenceOf(line string) string {
  var n int64= int64(len(line));
  var i int64= int64(0);
  for i < n && Deck_static_isSpace(int64(line[i])) {
    i = i + int64(1); 
  }
  if  i >= n {
    return ""
  }
  var c int64= int64(line[i]);
  if  c != int64(96) && c != int64(126) {
    return ""
  }
  var j int64= i;
  for j < n && int64(line[j]) == c {
    j = j + int64(1); 
  }
  if  j - i < int64(3) {
    return ""
  }
  return line[i:j]
}
func Deck_static_headingOf(line string) string {
  var n int64= int64(len(line));
  var h int64= int64(0);
  for h < n && int64(line[h]) == int64(35) {
    h = h + int64(1); 
  }
  if  h < int64(1) || h > int64(2) {
    return ""
  }
  if  h >= n {
    return ""
  }
  if  Deck_static_isSpace(int64(line[h])) == false {
    return ""
  }
  var k int64= h;
  for k < n && Deck_static_isSpace(int64(line[k])) {
    k = k + int64(1); 
  }
  var title string= Deck_static_trimEnd(line[k:n]);
  if  strings.HasSuffix(title, "}") {
    var body string= title[int64(0):(int64(len(title)) - int64(1))];
    var lastClose int64= int64(strings.LastIndex(body, "}"));
    var from int64= lastClose + int64(1);
    var rest string= body[from:int64(len(body))];
    var open int64= int64(strings.Index(rest, "{"));
    if  open >= int64(0) {
      title = title[int64(0):(from + open)]; 
    }
  }
  return strings.TrimSpace(title)
}
func Deck_static_trimEnd(s string) string {
  var n int64= int64(len(s));
  for n > int64(0) && Deck_static_isSpace(int64(s[(n - int64(1))])) {
    n = n - int64(1); 
  }
  return s[int64(0):n]
}
func Deck_static_outline(md string) *Outline {
  var out *Outline= CreateNew_Outline();
  var fence string= "";
  var lines []string= strings.Split(md, "\n");
  for _, raw := range lines {
    var line string= raw;
    if  strings.HasSuffix(line, "\r") {
      line = line[int64(0):(int64(len(line)) - int64(1))]; 
    }
    var f string= Deck_static_fenceOf(line);
    if  int64(len(f)) > int64(0) {
      if  int64(len(fence)) == int64(0) {
        fence = f; 
      } else {
        if  int64(f[int64(0)]) == int64(fence[int64(0)]) && int64(len(f)) >= int64(len(fence)) {
          fence = ""; 
        }
      }
      continue;
    }
    if  int64(len(fence)) > int64(0) {
      continue;
    }
    if  strings.HasPrefix(line, "#") {
      var n int64= int64(len(line));
      var h int64= int64(0);
      for h < n && int64(line[h]) == int64(35) {
        h = h + int64(1); 
      }
      if  (h == int64(1) || h == int64(2)) && h < n {
        if  Deck_static_isSpace(int64(line[h])) {
          out.titles = append(out.titles,Deck_static_headingOf(line)); 
        }
      }
    }
    Deck_static_mediaIn(line, out);
  }
  return out
}
func Deck_static_mediaIn(line string, out *Outline) () {
  var at int64= int64(strings.Index(line, "media/"));
  for at >= int64(0) {
    var start int64= at + int64(6);
    var n int64= int64(len(line));
    var e int64= start;
    for e < n && Deck_static_nameChar(int64(line[e])) {
      e = e + int64(1); 
    }
    if  e > start {
      var m string= line[start:e];
      if  Deck_static_inList(out.media, m) == false {
        out.media = append(out.media,m); 
      }
    }
    var rest string= line[start:n];
    var next int64= int64(strings.Index(rest, "media/"));
    if  next < int64(0) {
      at = int64(-1); 
    } else {
      at = start + next; 
    }
  }
}
func Deck_static_inList(list []string, s string) bool {
  for _, x := range list {
    if  x == s {
      return true
    }
  }
  return false
}
func Deck_static_warnings(md string, imageNames []string, storedNames []string) []string {
  var o *Outline= Deck_static_outline(md); _ = o
  var out []string = make([]string, 0);
  for _, m := range o.media {
    if  Deck_static_inList(imageNames, m) == false && Deck_static_inList(storedNames, m) == false {
      out = append(out,("media/" + m) + " is used in the Markdown but no image by that name was sent."); 
    }
  }
  for _, nm := range imageNames {
    if  Deck_static_inList(o.media, nm) == false {
      out = append(out,((("Image " + nm) + " was sent but the Markdown does not use media/") + nm) + "."); 
    }
  }
  return out
}
func Deck_static_privateHost(host string) bool {
  var h string= strings.ToLower(host);
  if  strings.HasPrefix(h, "[") && strings.HasSuffix(h, "]") {
    h = h[int64(1):(int64(len(h)) - int64(1))]; 
  }
  if  (h == "localhost" || strings.HasSuffix(h, ".localhost")) || (strings.HasSuffix(h, ".internal") || strings.HasSuffix(h, ".local")) {
    return true
  }
  if  ((strings.HasPrefix(h, "127.") || strings.HasPrefix(h, "10.")) || (strings.HasPrefix(h, "0.") || strings.HasPrefix(h, "169.254."))) || strings.HasPrefix(h, "192.168.") {
    return true
  }
  if  strings.HasPrefix(h, "172.") {
    var rest string= h[int64(4):int64(len(h))];
    var dot int64= int64(strings.Index(rest, "."));
    if  dot > int64(0) {
      var second *GoNullable = new(GoNullable); 
      var second__src *GoNullable = r_str_2_i64(rest[int64(0):dot]);
      second.value = second__src.value;
      second.has_value = second__src.has_value;
      if  second.has_value {
        var v int64= second.value.(int64);
        if  v >= int64(16) && v <= int64(31) {
          return true
        }
      }
    }
  }
  if  (h == "::1" || strings.HasPrefix(h, "fc")) || (strings.HasPrefix(h, "fd") || strings.HasPrefix(h, "fe80")) {
    return true
  }
  return false
}
func Deck_static_loadImages(host *McpHost, list []*MfJ) *Loaded {
  var res *Loaded= CreateNew_Loaded();
  if  int64(len(list)) > Deck_static_MAX_IMAGES() {
    res.err = ("At most " + strconv.FormatInt(Deck_static_MAX_IMAGES(), 10)) + " images per call."; 
    return res
  }
  for _, img := range list {
    var given string= img.str_("name");
    var name string= Deck_static_cleanName(given);
    if  int64(len(name)) == int64(0) {
      res.err = ("Image name \"" + given) + "\" is not usable: use letters, digits, \".\", \"-\" and \"_\"."; 
      return res
    }
    var _type string= Deck_static_typeOf(name, img.str_("mime_type"));
    var handle int64= int64(0);
    var size int64= int64(0);
    var b64 string= img.str_("data_base64");
    var url string= img.str_("url");
    if  int64(len(b64)) > int64(0) {
      if  strings.HasPrefix(b64, "data:") {
        var semi int64= int64(strings.Index(b64, ";base64,"));
        if  semi > int64(0) {
          if  int64(len(_type)) == int64(0) {
            _type = Deck_static_typeOf(name, b64[int64(5):semi]); 
          }
          b64 = b64[(semi + int64(8)):int64(len(b64))]; 
        }
      }
      var got *MfJ= J_static_parse(host.ImageFromBase64(b64)); _ = got
      handle = got.int_("handle", int64(0)); 
      size = got.int_("size", int64(0)); 
    } else {
      if  int64(len(url)) > int64(0) {
        var u *MfJ= J_static_parse(host.ParseURL(url)); _ = u
        if  u.isObj() == false {
          res.err = ((("Image " + name) + ": \"") + url) + "\" is not a URL."; 
          return res
        }
        var hostname string= u.str_("hostname");
        if  u.str_("scheme") != "https" || Deck_static_privateHost(hostname) {
          res.err = ("Image " + name) + ": only public https URLs are fetched."; 
          return res
        }
        var got_1 *MfJ= J_static_parse(host.ImageFromURL(url, Deck_static_MAX_IMAGE() + int64(1))); _ = got_1
        var status int64= got_1.int_("status", int64(0));
        if  status == int64(0) {
          res.err = ((("Image " + name) + ": ") + hostname) + " could not be fetched."; 
          return res
        }
        if  status < int64(200) || status > int64(299) {
          res.err = ((((("Image " + name) + ": ") + hostname) + " answered ") + strconv.FormatInt(status, 10)) + "."; 
          return res
        }
        var ct string= got_1.str_("type");
        if  int64(len(ct)) > int64(0) && strings.HasPrefix(ct, "image/") == false {
          res.err = ((("Image " + name) + ": the URL gave ") + ct) + ", not a picture."; 
          return res
        }
        if  got_1.int_("length", int64(0)) > Deck_static_MAX_IMAGE() {
          res.err = ("Image " + name) + " is larger than 5 MB."; 
          return res
        }
        handle = got_1.int_("handle", int64(0)); 
        size = got_1.int_("size", int64(0)); 
        if  int64(len(_type)) == int64(0) {
          _type = Deck_static_typeOf(name, ct); 
        }
      } else {
        res.err = ("Image " + name) + ": give either url or data_base64."; 
        return res
      }
    }
    if  size == int64(0) {
      res.err = ("Image " + name) + " is empty."; 
      return res
    }
    if  size > Deck_static_MAX_IMAGE() {
      res.err = ("Image " + name) + " is larger than 5 MB."; 
      return res
    }
    if  int64(len(_type)) == int64(0) {
      res.err = ("Image " + name) + ": unknown picture type; name it .png, .jpg, .gif, .webp or .svg."; 
      return res
    }
    var im *Img= CreateNew_Img();
    im.name = name; 
    im._type = _type; 
    im.handle = handle; 
    im.size = size; 
    res.imgs = append(res.imgs,im); 
  }
  return res
}
type HttpOut struct { 
  status int64 `json:"status"` 
  redirect string `json:"redirect"` 
  text string `json:"text"` 
  json *MfJ `json:"json"` 
  noStore bool `json:"noStore"` 
}

func CreateNew_HttpOut() *HttpOut {
  me := new(HttpOut)
  me.status = int64(200)
  me.redirect = ""
  me.text = ""
  me.json = CreateNew_MfJ()
  me.noStore = false
  return me;
}
func HttpOut_static_bad(error string, description string) *HttpOut {
  var o *HttpOut= CreateNew_HttpOut();
  o.status = int64(400); 
  o.json = MfJ_static_newObj(); 
  o.json.putStr("error", error);
  if  int64(len(description)) > int64(0) {
    o.json.putStr("error_description", description);
  }
  o.noStore = true; 
  return o
}
func HttpOut_static_of(status int64, json *MfJ) *HttpOut {
  var o *HttpOut= CreateNew_HttpOut();
  o.status = status; 
  o.json = json; 
  o.noStore = true; 
  return o
}
func HttpOut_static_redirectTo(url string) *HttpOut {
  var o *HttpOut= CreateNew_HttpOut();
  o.status = int64(302); 
  o.redirect = url; 
  return o
}
func HttpOut_static_plain(status int64, text string) *HttpOut {
  var o *HttpOut= CreateNew_HttpOut();
  o.status = status; 
  o.text = text; 
  return o
}
func HttpOut_static_fail() *HttpOut {
  var o *HttpOut= CreateNew_HttpOut();
  o.status = int64(500); 
  o.json = MfJ_static_newObj(); 
  o.json.putStr("error", "server_error");
  return o
}
type Who struct { 
  state int64 `json:"state"` 
  uid string `json:"uid"` 
  name string `json:"name"` 
}

func CreateNew_Who() *Who {
  me := new(Who)
  me.state = int64(0)
  me.uid = ""
  me.name = ""
  return me;
}
type OAuth struct { 
}

func CreateNew_OAuth() *OAuth {
  me := new(OAuth)
  return me;
}
func OAuth_static_SCOPE() string {
  return "decks"
}
func OAuth_static_CODE_TTL() int64 {
  return int64(600000)
}
func OAuth_static_REQUEST_TTL() int64 {
  return int64(900000)
}
func OAuth_static_ACCESS_TTL() int64 {
  return int64(3600000)
}
func OAuth_static_REFRESH_TTL() int64 {
  return int64(5184000000)
}
func OAuth_static_col(name string) string {
  return "mcp_oauth_" + name
}
func OAuth_static_loopback(u *MfJ) bool {
  var h string= u.str_("hostname");
  return u.str_("scheme") == "http" && ((h == "localhost" || h == "127.0.0.1") || h == "::1")
}
func OAuth_static_redirectAllowed(host *McpHost, uri string) bool {
  if  int64(strings.Index(uri, "#")) >= int64(0) {
    return false
  }
  var u *MfJ= J_static_parse(host.ParseURL(uri));
  if  u.isObj() == false {
    return false
  }
  var scheme string= u.str_("scheme");
  if  scheme == "https" || OAuth_static_loopback(u) {
    return true
  }
  if  ((scheme == "http" || scheme == "javascript") || (scheme == "data" || scheme == "file")) || (scheme == "vbscript" || scheme == "blob") {
    return false
  }
  return OAuth_static_schemeName(scheme)
}
func OAuth_static_schemeName(s string) bool {
  var n int64= int64(len(s));
  if  n == int64(0) {
    return false
  }
  var i int64= int64(0);
  for i < n {
    var c int64= int64(s[i]);
    var ok bool= c >= int64(97) && c <= int64(122);
    if  i > int64(0) {
      if  (c >= int64(48) && c <= int64(57) || c == int64(43)) || (c == int64(46) || c == int64(45)) {
        ok = true; 
      }
    }
    if  ok == false {
      return false
    }
    i = i + int64(1); 
  }
  return true
}
func OAuth_static_sameRedirect(host *McpHost, registered string, given string) bool {
  if  registered == given {
    return true
  }
  var a *MfJ= J_static_parse(host.ParseURL(registered));
  var b *MfJ= J_static_parse(host.ParseURL(given));
  if  a.isObj() == false || b.isObj() == false {
    return false
  }
  if  OAuth_static_loopback(a) == false || OAuth_static_loopback(b) == false {
    return false
  }
  return (a.str_("hostname") == b.str_("hostname") && a.str_("path") == b.str_("path")) && a.str_("search") == b.str_("search")
}
func OAuth_static_clientIdChars(id string) bool {
  var n int64= int64(len(id));
  return (n >= int64(8) && n <= int64(64)) && Deck_static_allAlnum(id)
}
func OAuth_static_client(host *McpHost, clientId string) *MfJ {
  if  strings.HasPrefix(clientId, "https://") {
    var u *MfJ= J_static_parse(host.ParseURL(clientId)); _ = u
    if  u.isObj() == false {
      return CreateNew_MfJ()
    }
    var hn string= u.str_("hostname");
    if  (Deck_static_privateHost(hn) || strings.HasPrefix(u.str_("host"), "[")) || strings.HasPrefix(hn, "0.") {
      return CreateNew_MfJ()
    }
    var got *MfJ= J_static_parse(host.FetchText(
      clientId,
      "application/json",
      int64(20001),
    )); _ = got
    var status int64= got.int_("status", int64(0));
    if  status < int64(200) || status > int64(299) {
      return CreateNew_MfJ()
    }
    var text string= got.str_("body");
    if  int64(len(text)) > int64(20000) {
      return CreateNew_MfJ()
    }
    var meta *MfJ= J_static_parse(text); _ = meta
    if  meta.isObj() == false || meta.str_("client_id") != clientId {
      return CreateNew_MfJ()
    }
    var uris *MfJ= meta.field("redirect_uris"); _ = uris
    if  uris.isArr() == false {
      return CreateNew_MfJ()
    }
    var allowed *MfJ= MfJ_static_newArr();
    for _, r := range uris.arr {
      if  r.kind == int64(3) {
        if  OAuth_static_redirectAllowed(host, r.str) {
          allowed.add(r);
        }
      }
    }
    var name string= meta.str_("client_name");
    if  int64(len(name)) == int64(0) {
      name = hn; 
    }
    var c *MfJ= MfJ_static_newObj();
    c.putStr("client_id", clientId);
    c.putStr("client_name", name);
    c.put("redirect_uris", allowed);
    return c
  }
  if  OAuth_static_clientIdChars(clientId) == false {
    return CreateNew_MfJ()
  }
  return J_static_parse(host.GetDoc(OAuth_static_col("clients"), clientId))
}
func OAuth_static_metadata(origin string) *MfJ {
  var m *MfJ= MfJ_static_newObj();
  m.putStr("issuer", origin);
  m.putStr("authorization_endpoint", origin + "/oauth/authorize");
  m.putStr("token_endpoint", origin + "/oauth/token");
  m.putStr("registration_endpoint", origin + "/oauth/register");
  m.put("response_types_supported", J_static_strs([]string {"code"}));
  m.put("grant_types_supported", J_static_strs([]string {"authorization_code", "refresh_token"}));
  m.put("code_challenge_methods_supported", J_static_strs([]string {"S256"}));
  m.put("token_endpoint_auth_methods_supported", J_static_strs([]string {"none"}));
  m.put("scopes_supported", J_static_strs([]string {"decks"}));
  m.putBool("client_id_metadata_document_supported", true);
  m.putStr("service_documentation", origin + "/connect.html");
  return m
}
func OAuth_static_resourceMetadata(origin string) *MfJ {
  var m *MfJ= MfJ_static_newObj();
  m.putStr("resource", origin + "/mcp");
  m.put("authorization_servers", J_static_strs([]string {origin}));
  m.put("scopes_supported", J_static_strs([]string {"decks"}));
  m.put("bearer_methods_supported", J_static_strs([]string {"header"}));
  m.putStr("resource_name", "Sliqtly");
  m.putStr("resource_documentation", origin + "/connect.html");
  return m
}
func OAuth_static_register(host *McpHost, body *MfJ) *HttpOut {
  var given *MfJ= body.field("redirect_uris"); _ = given
  var uris *MfJ= MfJ_static_newArr();
  var ok bool= given.isArr();
  if  ok {
    for _, r := range given.arr {
      var s string= JOut_static_text(r);
      if  r.kind == int64(3) {
        s = r.str; 
      }
      uris.add(MfJ_static_ofStr(s));
      if  OAuth_static_redirectAllowed(host, s) == false {
        ok = false; 
      }
    }
  }
  if  uris.count() == int64(0) || uris.count() > int64(10) {
    ok = false; 
  }
  if  ok == false {
    return HttpOut_static_bad("invalid_redirect_uri", "redirect_uris: https, a loopback http address, or an app scheme")
  }
  var name string= J_static_textOf(body, "client_name");
  if  int64(len(name)) == int64(0) {
    name = "MCP client"; 
  }
  if  int64(len(name)) > int64(100) {
    name = name[int64(0):int64(100)]; 
  }
  var created int64= host.NowMS();
  var id string= host.ShortID(int64(24));
  var doc *MfJ= MfJ_static_newObj();
  doc.putStr("client_id", id);
  doc.putStr("client_name", name);
  doc.put("redirect_uris", uris);
  doc.putInt("created", created);
  host.SetDoc(OAuth_static_col("clients"), id, JOut_static_text(doc))
  if  int64(len(host.Err())) > int64(0) {
    return HttpOut_static_fail()
  }
  var out *MfJ= MfJ_static_newObj();
  out.putStr("client_id", id);
  out.putStr("client_name", name);
  out.put("redirect_uris", uris);
  out.putInt("client_id_issued_at", created / int64(1000));
  out.put("grant_types", J_static_strs([]string {"authorization_code", "refresh_token"}));
  out.put("response_types", J_static_strs([]string {"code"}));
  out.putStr("token_endpoint_auth_method", "none");
  out.putStr("scope", "decks");
  return HttpOut_static_of(int64(201), out)
}
func OAuth_static_authorize(host *McpHost, q *MfJ, origin string) *HttpOut {
  var c *MfJ= CreateNew_MfJ(); _ = c
  var cid string= q.str_("client_id");
  if  int64(len(cid)) > int64(0) {
    c = OAuth_static_client(host, cid); 
  }
  if  c.isObj() == false {
    return HttpOut_static_plain(int64(400), "Unknown client_id.")
  }
  var registered []string= J_static_strList(c.field("redirect_uris"));
  var redirect string= q.str_("redirect_uri");
  if  int64(len(redirect)) == int64(0) && int64(len(registered)) == int64(1) {
    redirect = registered[int64(0)]; 
  }
  var known bool= false;
  for _, r := range registered {
    if  OAuth_static_sameRedirect(host, r, redirect) {
      known = true; 
    }
  }
  if  int64(len(redirect)) == int64(0) || known == false {
    return HttpOut_static_plain(int64(400), "redirect_uri is not registered for this client.")
  }
  if  q.str_("response_type") != "code" {
    return OAuth_static_back(host, redirect, q, origin, "unsupported_response_type", "")
  }
  if  int64(len(q.str_("code_challenge"))) == int64(0) || q.str_("code_challenge_method") != "S256" {
    return OAuth_static_back(
      host,
      redirect,
      q,
      origin,
      "invalid_request",
      "PKCE with S256 is required",
    )
  }
  var rid string= host.ShortID(int64(24));
  var req *MfJ= MfJ_static_newObj();
  req.put("client_id", c.field("client_id"));
  req.put("client_name", c.field("client_name"));
  req.putStr("redirect_uri", redirect);
  req.put("state", OAuth_static_orNull(q.str_("state")));
  req.putStr("code_challenge", q.str_("code_challenge"));
  req.put("resource", OAuth_static_orNull(q.str_("resource")));
  req.putStr("origin", origin);
  req.putInt("exp", host.NowMS() + OAuth_static_REQUEST_TTL());
  host.SetDoc(OAuth_static_col("requests"), rid, JOut_static_text(req))
  if  int64(len(host.Err())) > int64(0) {
    return HttpOut_static_fail()
  }
  var to *MfJ= J_static_parse(host.ParseURL(redirect));
  var where string= to.str_("scheme") + " app";
  if  OAuth_static_loopback(to) {
    where = "this computer"; 
  } else {
    if  to.str_("scheme") == "https" {
      where = to.str_("host"); 
    }
  }
  return HttpOut_static_redirectTo(((((((origin + "/oauth.html?request=") + rid) + "&client=") + host.URIEncode(c.str_("client_name"))) + "&to=") + host.URIEncode(where)))
}
func OAuth_static_back(host *McpHost, redirect string, q *MfJ, origin string, error string, description string) *HttpOut {
  var p *MfJ= MfJ_static_newObj();
  p.putStr("error", error);
  if  int64(len(description)) > int64(0) {
    p.putStr("error_description", description);
  }
  var state string= q.str_("state");
  if  int64(len(state)) > int64(0) {
    p.putStr("state", state);
  }
  p.putStr("iss", origin);
  return HttpOut_static_redirectTo(host.URLSet(redirect, JOut_static_text(p)))
}
func OAuth_static_orNull(s string) *MfJ {
  if  int64(len(s)) == int64(0) {
    return CreateNew_MfJ()
  }
  return MfJ_static_ofStr(s)
}
func OAuth_static_approve(host *McpHost, body *MfJ) *HttpOut {
  var rid string= J_static_textOf(body, "request");
  if  int64(len(rid)) != int64(24) || Deck_static_allAlnum(rid) == false {
    var e *MfJ= MfJ_static_newObj();
    e.putStr("error", "invalid_request");
    return HttpOut_static_of(int64(400), e)
  }
  var r *MfJ= J_static_parse(host.GetDoc(OAuth_static_col("requests"), rid)); _ = r
  if  int64(len(host.Err())) > int64(0) {
    return HttpOut_static_fail()
  }
  if  r.isObj() == false {
    return HttpOut_static_bad("invalid_request", "The sign-in request has expired. Start again from your assistant.")
  }
  if  r.num_("exp", 0.0) < float64( host.NowMS() ) {
    host.DeleteDoc(OAuth_static_col("requests"), rid)
    return HttpOut_static_bad("invalid_request", "The sign-in request has expired. Start again from your assistant.")
  }
  var p *MfJ= MfJ_static_newObj();
  var state string= r.str_("state");
  if  int64(len(state)) > int64(0) {
    p.putStr("state", state);
  }
  p.putStr("iss", r.str_("origin"));
  if  J_static_truthy(body.field("deny")) {
    host.DeleteDoc(OAuth_static_col("requests"), rid)
    p.putStr("error", "access_denied");
    var d *MfJ= MfJ_static_newObj();
    d.putStr("redirect", host.URLSet(r.str_("redirect_uri"), JOut_static_text(p)));
    return HttpOut_static_of(int64(200), d)
  }
  var who *MfJ= J_static_parse(host.VerifyIDToken(J_static_textOf(body, "id_token"))); _ = who
  if  who.isObj() == false {
    var e2 *MfJ= MfJ_static_newObj();
    e2.putStr("error", "invalid_token");
    e2.putStr("error_description", "Google sign-in could not be verified.");
    return HttpOut_static_of(int64(401), e2)
  }
  host.DeleteDoc(OAuth_static_col("requests"), rid)
  var code string= host.ShortID(int64(32));
  var name string= who.str_("name");
  if  int64(len(name)) == int64(0) {
    name = who.str_("email"); 
  }
  var c *MfJ= MfJ_static_newObj();
  c.putStr("uid", who.str_("uid"));
  c.putStr("name", name);
  c.put("client_id", r.field("client_id"));
  c.put("redirect_uri", r.field("redirect_uri"));
  c.put("code_challenge", r.field("code_challenge"));
  c.put("resource", r.field("resource"));
  c.putInt("exp", host.NowMS() + OAuth_static_CODE_TTL());
  host.SetDoc(OAuth_static_col("codes"), host.SHA256Hex(code), JOut_static_text(c))
  if  int64(len(host.Err())) > int64(0) {
    return HttpOut_static_fail()
  }
  p.putStr("code", code);
  var ok *MfJ= MfJ_static_newObj();
  ok.putStr("redirect", host.URLSet(r.str_("redirect_uri"), JOut_static_text(p)));
  return HttpOut_static_of(int64(200), ok)
}
func OAuth_static_issue(host *McpHost, from *MfJ) *HttpOut {
  var access string= host.ShortID(int64(32));
  var refresh string= host.ShortID(int64(40));
  var now int64= host.NowMS();
  var a *MfJ= OAuth_static_grant(from);
  a.putStr("kind", "access");
  a.putInt("exp", now + OAuth_static_ACCESS_TTL());
  var r *MfJ= OAuth_static_grant(from);
  r.putStr("kind", "refresh");
  r.putInt("exp", now + OAuth_static_REFRESH_TTL());
  host.SetDoc(OAuth_static_col("tokens"), host.SHA256Hex(access), JOut_static_text(a))
  host.SetDoc(OAuth_static_col("tokens"), host.SHA256Hex(refresh), JOut_static_text(r))
  if  int64(len(host.Err())) > int64(0) {
    return HttpOut_static_fail()
  }
  var out *MfJ= MfJ_static_newObj();
  out.putStr("access_token", access);
  out.putStr("token_type", "Bearer");
  out.putInt("expires_in", OAuth_static_ACCESS_TTL() / int64(1000));
  out.putStr("refresh_token", refresh);
  out.putStr("scope", "decks");
  return HttpOut_static_of(int64(200), out)
}
func OAuth_static_grant(from *MfJ) *MfJ {
  var g *MfJ= MfJ_static_newObj();
  g.put("uid", from.field("uid"));
  g.put("name", from.field("name"));
  g.put("client_id", from.field("client_id"));
  g.put("resource", from.field("resource"));
  return g
}
func OAuth_static_token(host *McpHost, b *MfJ) *HttpOut {
  var grantType string= J_static_textOf(b, "grant_type");
  var now float64= float64( host.NowMS() );
  if  grantType == "authorization_code" {
    var id string= host.SHA256Hex(J_static_textOf(b, "code"));
    var c *MfJ= J_static_parse(host.GetDoc(OAuth_static_col("codes"), id));
    if  int64(len(host.Err())) > int64(0) {
      return HttpOut_static_fail()
    }
    if  c.isObj() == false {
      return HttpOut_static_bad("invalid_grant", "")
    }
    host.DeleteDoc(OAuth_static_col("codes"), id)
    if  c.num_("exp", 0.0) < now {
      return HttpOut_static_bad("invalid_grant", "code expired")
    }
    var cid string= J_static_textOf(b, "client_id");
    if  int64(len(cid)) > int64(0) && cid != c.str_("client_id") {
      return HttpOut_static_bad("invalid_grant", "client_id does not match")
    }
    var ru string= J_static_textOf(b, "redirect_uri");
    if  int64(len(ru)) == int64(0) || OAuth_static_sameRedirect(host, c.str_("redirect_uri"), ru) == false {
      return HttpOut_static_bad("invalid_grant", "redirect_uri does not match")
    }
    var v string= J_static_textOf(b, "code_verifier");
    if  int64(len(v)) == int64(0) || host.SHA256B64URL(v) != c.str_("code_challenge") {
      return HttpOut_static_bad("invalid_grant", "PKCE verification failed")
    }
    return OAuth_static_issue(host, c)
  }
  if  grantType == "refresh_token" {
    var id2 string= host.SHA256Hex(J_static_textOf(b, "refresh_token"));
    var t *MfJ= J_static_parse(host.GetDoc(OAuth_static_col("tokens"), id2));
    if  int64(len(host.Err())) > int64(0) {
      return HttpOut_static_fail()
    }
    if  t.isObj() == false || t.str_("kind") != "refresh" {
      return HttpOut_static_bad("invalid_grant", "")
    }
    host.DeleteDoc(OAuth_static_col("tokens"), id2)
    if  t.num_("exp", 0.0) < now {
      return HttpOut_static_bad("invalid_grant", "refresh token expired")
    }
    var cid2 string= J_static_textOf(b, "client_id");
    if  int64(len(cid2)) > int64(0) && cid2 != t.str_("client_id") {
      return HttpOut_static_bad("invalid_grant", "client_id does not match")
    }
    return OAuth_static_issue(host, t)
  }
  return HttpOut_static_bad("unsupported_grant_type", "")
}
func OAuth_static_who(host *McpHost, header string) *Who {
  var w *Who= CreateNew_Who();
  var h string= strings.TrimSpace(header);
  if  int64(len(h)) < int64(8) {
    return w
  }
  if  strings.ToLower(h[int64(0):int64(7)]) != "bearer " {
    return w
  }
  var tok string= strings.TrimSpace(h[int64(7):int64(len(h))]);
  if  int64(len(tok)) == int64(0) || int64(strings.Index(tok, " ")) >= int64(0) {
    return w
  }
  var t *MfJ= J_static_parse(host.GetDoc(OAuth_static_col("tokens"), host.SHA256Hex(tok))); _ = t
  if  int64(len(host.Err())) > int64(0) {
    w.state = int64(3); 
    return w
  }
  if  (t.isObj() == false || t.str_("kind") != "access") || t.num_("exp", 0.0) < float64( host.NowMS() ) {
    w.state = int64(2); 
    return w
  }
  w.state = int64(1); 
  w.uid = t.str_("uid"); 
  w.name = t.str_("name"); 
  return w
}
type Created struct { 
  id string `json:"id"` 
  key string `json:"key"` 
  err string `json:"err"` 
}

func CreateNew_Created() *Created {
  me := new(Created)
  me.id = ""
  me.key = ""
  me.err = ""
  return me;
}
type DeckPatch struct { 
  hasName bool `json:"hasName"` 
  name string `json:"name"` 
  hasMd bool `json:"hasMd"` 
  md string `json:"md"` 
  hasTheme bool `json:"hasTheme"` 
  theme string `json:"theme"` 
  cssMode int64 `json:"cssMode"` 
  css string `json:"css"` 
}

func CreateNew_DeckPatch() *DeckPatch {
  me := new(DeckPatch)
  me.hasName = false
  me.name = ""
  me.hasMd = false
  me.md = ""
  me.hasTheme = false
  me.theme = ""
  me.cssMode = int64(0)
  me.css = ""
  return me;
}
type Store struct { 
}

func CreateNew_Store() *Store {
  me := new(Store)
  return me;
}
func Store_static_serverTime() *MfJ {
  var t *MfJ= MfJ_static_newObj();
  t.putBool("$serverTime", true);
  return t
}
func Store_static_validId(id string) bool {
  var n int64= int64(len(id));
  if  n < int64(1) || n > int64(64) {
    return false
  }
  return Deck_static_allAlnum(id)
}
func Store_static_create(host *McpHost, name string, md string, theme string, hasCss bool, css string, imgs []*Img, owner string) *Created {
  var out *Created= CreateNew_Created();
  var id string= host.ShortID(int64(10));
  var key string= host.ShortID(int64(24));
  var k *MfJ= MfJ_static_newObj();
  k.putStr("hash", host.SHA256Hex(key));
  k.put("created", Store_static_serverTime());
  host.SetDoc("mcp_keys", id, JOut_static_text(k))
  var e1 string= host.Err();
  if  int64(len(e1)) > int64(0) {
    out.err = e1; 
    return out
  }
  var files *MfJ= Store_static_upload(host, id, imgs);
  var e2 string= host.Err();
  if  int64(len(e2)) > int64(0) {
    out.err = e2; 
    return out
  }
  var doc *MfJ= MfJ_static_newObj();
  doc.putStr("name", name);
  doc.putStr("md", md);
  doc.putStr("theme", theme);
  if  hasCss {
    doc.putStr("css", css);
  } else {
    doc.put("css", CreateNew_MfJ());
  }
  doc.putStr("owner", owner);
  doc.putStr("deck", "mcp");
  doc.putStr("source", "mcp");
  doc.put("files", files);
  doc.put("created", Store_static_serverTime());
  host.SetDoc("shares", id, JOut_static_text(doc))
  var e3 string= host.Err();
  if  int64(len(e3)) > int64(0) {
    out.err = e3; 
    return out
  }
  out.id = id; 
  out.key = key; 
  return out
}
func Store_static_update(host *McpHost, id string, checkKey bool, key string, p *DeckPatch, imgs []*Img) *MfJ {
  if  Store_static_validId(id) == false {
    return CreateNew_MfJ()
  }
  if  checkKey {
    var kd *MfJ= J_static_parse(host.GetDoc("mcp_keys", id)); _ = kd
    if  kd.isObj() == false {
      return CreateNew_MfJ()
    }
    if  kd.str_("hash") != host.SHA256Hex(key) {
      return CreateNew_MfJ()
    }
  }
  var cur *MfJ= J_static_parse(host.GetDoc("shares", id));
  if  cur.isObj() == false {
    return CreateNew_MfJ()
  }
  var added *MfJ= Store_static_upload(host, id, imgs); _ = added
  if  int64(len(host.Err())) > int64(0) {
    return CreateNew_MfJ()
  }
  var files *MfJ= MfJ_static_newArr();
  var i int64 = 0;  
  for ; i < int64(len(cur.list("files"))) ; i++ {
    f := cur.list("files")[i]
    var path string= f.str_("path");
    var replaced bool= false;
    for _, a := range added.arr {
      if  a.str_("path") == path {
        replaced = true; 
      }
    }
    if  replaced == false {
      files.add(f);
    }
  }
  for _, a2 := range added.arr {
    files.add(a2);
  }
  var patch *MfJ= MfJ_static_newObj();
  patch.put("files", files);
  patch.put("updated", Store_static_serverTime());
  if  p.hasName {
    patch.putStr("name", p.name);
  }
  if  p.hasMd {
    patch.putStr("md", p.md);
  }
  if  p.hasTheme {
    patch.putStr("theme", p.theme);
  }
  if  p.cssMode == int64(1) {
    patch.putStr("css", p.css);
  }
  if  p.cssMode == int64(2) {
    patch.put("css", CreateNew_MfJ());
  }
  host.UpdateDoc("shares", id, JOut_static_text(patch))
  if  int64(len(host.Err())) > int64(0) {
    return CreateNew_MfJ()
  }
  var m int64 = 0;  
  for ; m < int64(len(patch.ks)) ; m++ {
    pk := patch.ks[m]
    cur.put(pk, patch.field(pk));
  }
  return cur
}
func Store_static_get(host *McpHost, id string) *MfJ {
  if  Store_static_validId(id) == false {
    return CreateNew_MfJ()
  }
  return J_static_parse(host.GetDoc("shares", id))
}
func Store_static_list(host *McpHost, uid string) []*MfJ {
  var all *MfJ= J_static_parse(host.QueryEq("shares", "owner", uid)); _ = all
  var docs []*MfJ = make([]*MfJ, 0);
  for _, d := range all.arr {
    docs = append(docs,d); 
  }
  var n int64= int64(len(docs));
  var a int64= int64(1);
  for a < n {
    var cur *MfJ= docs[a];
    var t float64= Store_static_stamp(cur);
    var b int64= a - int64(1);
    var going bool= true;
    for b >= int64(0) && going {
      var prev *MfJ= docs[b];
      if  Store_static_stamp(prev) < t {
        docs[b + int64(1)] = prev;
        b = b - int64(1); 
      } else {
        going = false; 
      }
    }
    docs[b + int64(1)] = cur;
    a = a + int64(1); 
  }
  var out []*MfJ = make([]*MfJ, 0);
  var j int64 = 0;  
  for ; j < int64(len(docs)) ; j++ {
    d2 := docs[j]
    if  j < int64(50) {
      out = append(out,d2); 
    }
  }
  return out
}
func Store_static_stamp(d *MfJ) float64 {
  var u float64= d.num_("updated", 0.0);
  if  u != 0.0 {
    return u
  }
  return d.num_("created", 0.0)
}
func Store_static_upload(host *McpHost, id string, imgs []*Img) *MfJ {
  var out *MfJ= MfJ_static_newArr();
  for _, img := range imgs {
    var path string= "media/" + img.name;
    var name string= (("shares/" + id) + "/") + path;
    var token string= host.UUID();
    host.Upload(img.handle, name, img._type, token)
    if  int64(len(host.Err())) > int64(0) {
      return out
    }
    var f *MfJ= MfJ_static_newObj();
    f.putStr("path", path);
    f.putStr("type", img._type);
    f.putInt("size", img.size);
    f.putStr("url", (((("https://firebasestorage.googleapis.com/v0/b/" + host.Bucket()) + "/o/") + host.URIEncode(name)) + "?alt=media&token=") + token);
    out.add(f);
  }
  return out
}
type Caller struct { 
  signedIn bool `json:"signedIn"` 
  uid string `json:"uid"` 
  name string `json:"name"` 
  signIn string `json:"signIn"` 
  who string `json:"who"` 
}

func CreateNew_Caller() *Caller {
  me := new(Caller)
  me.signedIn = false
  me.uid = ""
  me.name = ""
  me.signIn = ""
  me.who = ""
  return me;
}
type Tools struct { 
}

func CreateNew_Tools() *Tools {
  me := new(Tools)
  return me;
}
func Tools_static_PREVIEW_URI() string {
  return "ui://sliqtly/preview.html"
}
func Tools_static_APP_MIME() string {
  return "text/html;profile=mcp-app"
}
func Tools_static_frames(base string) []string {
  var out []string = make([]string, 0);
  out = append(out,base); 
  if  base != "https://sliqtly.com" {
    out = append(out,"https://sliqtly.com"); 
  }
  if  base != "https://sliqtly.web.app" {
    out = append(out,"https://sliqtly.web.app"); 
  }
  return out
}
func Tools_static_either() *MfJ {
  var a *MfJ= MfJ_static_newArr();
  var n *MfJ= MfJ_static_newObj();
  n.putStr("type", "noauth");
  a.add(n);
  a.add(Tools_static_oauthScheme());
  return a
}
func Tools_static_oauthScheme() *MfJ {
  var o *MfJ= MfJ_static_newObj();
  o.putStr("type", "oauth2");
  o.put("scopes", J_static_strs([]string {"decks"}));
  return o
}
func Tools_static_uiMeta() *MfJ {
  var m *MfJ= MfJ_static_newObj();
  m.put("securitySchemes", Tools_static_either());
  var ui *MfJ= MfJ_static_newObj();
  ui.putStr("resourceUri", Tools_static_PREVIEW_URI());
  m.put("ui", ui);
  m.putStr("ui/resourceUri", Tools_static_PREVIEW_URI());
  m.putStr("openai/outputTemplate", Tools_static_PREVIEW_URI());
  m.putBool("openai/widgetAccessible", false);
  return m
}
func Tools_static_prop(_type string, desc string) *MfJ {
  var p *MfJ= MfJ_static_newObj();
  p.putStr("type", _type);
  if  int64(len(desc)) > int64(0) {
    p.putStr("description", desc);
  }
  return p
}
func Tools_static_schema(props *MfJ, required []string) *MfJ {
  var s *MfJ= MfJ_static_newObj();
  s.putStr("type", "object");
  s.put("properties", props);
  if  int64(len(required)) > int64(0) {
    s.put("required", J_static_strs(required));
  }
  s.putBool("additionalProperties", false);
  s.putStr("$schema", "http://json-schema.org/draft-07/schema#");
  return s
}
func Tools_static_deckFields(p *MfJ) () {
  var theme *MfJ= Tools_static_prop("string", "Theme: aurora (default), nebula, carbon, ember, midnight (dark); corporate, editorial (light)");
  theme.put("enum", J_static_strs(Deck_static_THEMES()));
  p.put("theme", theme);
  p.put("css", Tools_static_prop("string", "CSS rules added on top of the theme (selectors: page, document, h1, h2, p, list, li, code, table, chart, diagram, .lead …). See sliqtly_guide."));
  var mode *MfJ= Tools_static_prop("string", "extend (default): css is added after the theme's rules. replace: css is the whole stylesheet.");
  mode.put("enum", J_static_strs([]string {"extend", "replace"}));
  p.put("css_mode", mode);
  var ip *MfJ= MfJ_static_newObj();
  ip.put("name", Tools_static_prop("string", "File name the Markdown uses as media/<name>, e.g. \"team.jpg\" → ![](media/team.jpg)"));
  ip.put("url", Tools_static_prop("string", "A public https URL of the picture"));
  ip.put("data_base64", Tools_static_prop("string", "The picture's bytes as base64 (instead of url)"));
  ip.put("mime_type", Tools_static_prop("string", "image/png, image/jpeg, image/gif, image/webp or image/svg+xml; inferred from the name when left out"));
  var item *MfJ= MfJ_static_newObj();
  item.putStr("type", "object");
  item.put("properties", ip);
  item.put("required", J_static_strs([]string {"name"}));
  var images *MfJ= Tools_static_prop("array", "Pictures the Markdown refers to as media/<name>");
  images.put("items", item);
  p.put("images", images);
}
func Tools_static_annotations(readOnly bool, destructive int64, idempotent bool, openWorld bool) *MfJ {
  var a *MfJ= MfJ_static_newObj();
  a.putBool("readOnlyHint", readOnly);
  if  destructive == int64(0) {
    a.putBool("destructiveHint", false);
  }
  if  destructive == int64(1) {
    a.putBool("destructiveHint", true);
  }
  if  idempotent || readOnly == false {
    a.putBool("idempotentHint", idempotent);
  }
  a.putBool("openWorldHint", openWorld);
  return a
}
func Tools_static_tool(name string, title string, desc string, schema *MfJ, ann *MfJ, meta *MfJ) *MfJ {
  var t *MfJ= MfJ_static_newObj();
  t.putStr("name", name);
  t.putStr("title", title);
  t.putStr("description", desc);
  t.put("inputSchema", schema);
  t.put("annotations", ann);
  t.put("_meta", meta);
  return t
}
func Tools_static_list() *MfJ {
  var none []string = make([]string, 0);
  var eitherMeta *MfJ= MfJ_static_newObj();
  eitherMeta.put("securitySchemes", Tools_static_either());
  var tools *MfJ= MfJ_static_newArr();
  tools.add(Tools_static_tool(
    "sliqtly_guide",
    "Sliqtly syntax guide",
    "How to write a Sliqtly deck: slide structure, build animations, effects, pictures, charts (Vega-Lite), diagrams (Mermaid, Graphviz), math, themes and the CSS selectors. Read before the first create_presentation.",
    Tools_static_schema(MfJ_static_newObj(), none),
    Tools_static_annotations(true, int64(-1), false, false),
    eitherMeta,
  ));
  var cp *MfJ= MfJ_static_newObj();
  var title *MfJ= Tools_static_prop("string", "The presentation's name");
  title.putInt("maxLength", int64(200));
  cp.put("title", title);
  cp.put("markdown", Tools_static_prop("string", "The whole deck as Sliqtly Markdown"));
  Tools_static_deckFields(cp);
  tools.add(Tools_static_tool(
    "create_presentation",
    "Create a presentation",
    "Create a Sliqtly slide presentation from Markdown (# title slide, ## per slide), an optional theme, extra CSS and pictures. Returns a link that opens the presentation and a link to edit a copy in the Sliqtly editor.",
    Tools_static_schema(cp, []string {"title", "markdown"}),
    Tools_static_annotations(false, int64(0), false, true),
    Tools_static_uiMeta(),
  ));
  var up *MfJ= MfJ_static_newObj();
  up.put("deck_id", Tools_static_prop("string", "deck_id from create_presentation"));
  up.put("edit_key", Tools_static_prop("string", "edit_key from create_presentation; not needed when signed in as the presentation's owner"));
  var title2 *MfJ= Tools_static_prop("string", "");
  title2.putInt("maxLength", int64(200));
  up.put("title", title2);
  up.put("markdown", Tools_static_prop("string", "The whole deck as Sliqtly Markdown"));
  Tools_static_deckFields(up);
  tools.add(Tools_static_tool(
    "update_presentation",
    "Update a presentation",
    "Change a presentation made with create_presentation, keeping its link. Send only what changes: markdown replaces the whole text; images are added (or replace pictures of the same name).",
    Tools_static_schema(up, []string {"deck_id"}),
    Tools_static_annotations(false, int64(1), true, true),
    Tools_static_uiMeta(),
  ));
  var gp *MfJ= MfJ_static_newObj();
  gp.put("deck_id", Tools_static_prop("string", "The id in the share link /s/<id>"));
  tools.add(Tools_static_tool(
    "get_presentation",
    "Read a presentation",
    "Read a Sliqtly presentation's Markdown, theme, CSS and picture list by its deck_id (the id in https://sliqtly.com/s/<id>), to revise it.",
    Tools_static_schema(gp, []string {"deck_id"}),
    Tools_static_annotations(true, int64(-1), false, false),
    eitherMeta,
  ));
  var listMeta *MfJ= MfJ_static_newObj();
  var only *MfJ= MfJ_static_newArr();
  only.add(Tools_static_oauthScheme());
  listMeta.put("securitySchemes", only);
  tools.add(Tools_static_tool(
    "list_presentations",
    "List my presentations",
    "List the signed-in user's own Sliqtly presentations (newest first) with their links and deck_ids. Needs sign-in.",
    Tools_static_schema(MfJ_static_newObj(), none),
    Tools_static_annotations(true, int64(-1), false, false),
    listMeta,
  ));
  return tools
}
func Tools_static_csp(base string) *MfJ {
  var frames []string= Tools_static_frames(base);
  var resources []string= Tools_static_frames(base);
  resources = append(resources,"https://www.gstatic.com"); 
  var connects []string= Tools_static_frames(base);
  connects = append(connects,"https://firestore.googleapis.com"); 
  connects = append(connects,"https://firebasestorage.googleapis.com"); 
  var c *MfJ= MfJ_static_newObj();
  c.put("frameDomains", J_static_strs(frames));
  c.put("resourceDomains", J_static_strs(resources));
  c.put("connectDomains", J_static_strs(connects));
  return c
}
func Tools_static_uiCsp(base string) *MfJ {
  var ui *MfJ= MfJ_static_newObj();
  ui.put("csp", Tools_static_csp(base));
  ui.putBool("prefersBorder", false);
  return ui
}
func Tools_static_resources(base string) *MfJ {
  var r *MfJ= MfJ_static_newObj();
  r.putStr("uri", Tools_static_PREVIEW_URI());
  r.putStr("name", "preview");
  r.putStr("title", "Sliqtly presentation");
  r.putStr("description", "Shows the presentation inline");
  r.putStr("mimeType", Tools_static_APP_MIME());
  var meta *MfJ= MfJ_static_newObj();
  meta.put("ui", Tools_static_uiCsp(base));
  r.put("_meta", meta);
  var a *MfJ= MfJ_static_newArr();
  a.add(r);
  return a
}
func Tools_static_read(host *McpHost, uri string) *MfJ {
  if  uri != Tools_static_PREVIEW_URI() {
    return CreateNew_MfJ()
  }
  var base string= host.BaseURL();
  var c *MfJ= MfJ_static_newObj();
  c.putStr("uri", uri);
  c.putStr("mimeType", Tools_static_APP_MIME());
  c.putStr("text", host.Asset("preview.html"));
  var meta *MfJ= MfJ_static_newObj();
  meta.put("ui", Tools_static_uiCsp(base));
  var csp *MfJ= Tools_static_csp(base); _ = csp
  var w *MfJ= MfJ_static_newObj();
  w.put("connect_domains", csp.field("connectDomains"));
  w.put("resource_domains", csp.field("resourceDomains"));
  w.put("frame_domains", csp.field("frameDomains"));
  meta.put("openai/widgetCSP", w);
  meta.putStr("openai/widgetDescription", "The Sliqtly presentation, playable inline.");
  meta.putBool("openai/widgetPrefersBorder", true);
  c.put("_meta", meta);
  var contents *MfJ= MfJ_static_newArr();
  contents.add(c);
  var out *MfJ= MfJ_static_newObj();
  out.put("contents", contents);
  return out
}
func Tools_static_text(s string) *MfJ {
  var c *MfJ= MfJ_static_newObj();
  c.putStr("type", "text");
  c.putStr("text", s);
  var a *MfJ= MfJ_static_newArr();
  a.add(c);
  return a
}
func Tools_static_fail(message string) *MfJ {
  var r *MfJ= MfJ_static_newObj();
  r.put("content", Tools_static_text(message));
  r.putBool("isError", true);
  return r
}
func Tools_static_links(out *MfJ, base string, id string) () {
  out.putStr("share_url", (base + "/s/") + id);
  out.putStr("edit_url", ((base + "/s/") + id) + "?edit");
}
func Tools_static_result(caller *Caller, out *MfJ, verb string) *MfJ {
  var lines []string = make([]string, 0);
  lines = append(lines,((((((verb + ": \"") + out.str_("title")) + "\" (") + out.str_("slides")) + " slides, theme ") + out.str_("theme")) + ")."); 
  lines = append(lines,"Presentation: " + out.str_("share_url")); 
  lines = append(lines,"Open in the editor: " + out.str_("edit_url")); 
  if  caller.signedIn {
    var who string= caller.name;
    if  int64(len(who)) == int64(0) {
      who = "the signed-in user"; 
    }
    lines = append(lines,("Saved in the Sliqtly account of " + who) + "."); 
  }
  if  out.has("deck_id") {
    lines = append(lines,"deck_id: " + out.str_("deck_id")); 
  }
  if  out.has("edit_key") {
    lines = append(lines,("edit_key: " + out.str_("edit_key")) + " (needed for update_presentation; do not show it to others)"); 
  }
  var i int64 = 0;  
  for ; i < int64(len(J_static_strList(out.field("warnings")))) ; i++ {
    w := J_static_strList(out.field("warnings"))[i]
    lines = append(lines,"Note: " + w); 
  }
  lines = append(lines,"Give the user the presentation link."); 
  var r *MfJ= MfJ_static_newObj();
  r.put("content", Tools_static_text(strings.Join(lines, "\n")));
  r.put("structuredContent", out);
  r.put("_meta", Tools_static_uiMeta());
  return r
}
func Tools_static_checkArgs(a *MfJ, required []string) string {
  if  a.kind != int64(5) && a.kind != int64(0) {
    return "Invalid arguments: expected an object."
  }
  for _, r := range required {
    var __REGx1 *MfJ= a.field(r); _ = __REGx1
    if  __REGx1.kind != int64(3) {
      return ("Invalid arguments: " + r) + " is required."
    }
  }
  var j int64 = 0;  
  for ; j < int64(len([]string {"title", "markdown", "theme", "css", "css_mode", "deck_id", "edit_key"})) ; j++ {
    k := []string {"title", "markdown", "theme", "css", "css_mode", "deck_id", "edit_key"}[j]
    var v *MfJ= a.field(k); _ = v
    if  v.kind != int64(0) && v.kind != int64(3) {
      return ("Invalid arguments: " + k) + " is a string."
    }
  }
  var title *MfJ= a.field("title"); _ = title
  if  title.kind == int64(3) && Tools_static_chars(title.str) > int64(200) {
    return "Invalid arguments: title is longer than 200 characters."
  }
  var theme *MfJ= a.field("theme"); _ = theme
  if  theme.kind == int64(3) && Deck_static_inList(Deck_static_THEMES(), theme.str) == false {
    return ("Invalid arguments: theme is one of " + strings.Join(Deck_static_THEMES(), ", ")) + "."
  }
  var mode *MfJ= a.field("css_mode"); _ = mode
  if  mode.kind == int64(3) && (mode.str != "extend" && mode.str != "replace") {
    return "Invalid arguments: css_mode is extend or replace."
  }
  var images *MfJ= a.field("images"); _ = images
  if  images.kind != int64(0) && images.kind != int64(4) {
    return "Invalid arguments: images is a list."
  }
  for _, img := range images.arr {
    if  img.isObj() == false {
      return "Invalid arguments: every image is an object."
    }
    var __REGx2 *MfJ= img.field("name"); _ = __REGx2
    if  __REGx2.kind != int64(3) {
      return "Invalid arguments: every image needs a name."
    }
    var m int64 = 0;  
    for ; m < int64(len([]string {"url", "data_base64", "mime_type"})) ; m++ {
      f := []string {"url", "data_base64", "mime_type"}[m]
      var fv *MfJ= img.field(f); _ = fv
      if  fv.kind != int64(0) && fv.kind != int64(3) {
        return ("Invalid arguments: image " + f) + " is a string."
      }
    }
  }
  return ""
}
func Tools_static_chars(s string) int64 {
  var n int64= int64(len(s));
  var count int64= int64(0);
  var i int64= int64(0);
  for i < n {
    var c int64= int64(s[i]);
    if  c < int64(128) || c >= int64(192) {
      count = count + int64(1); 
    }
    i = i + int64(1); 
  }
  return count
}
func Tools_static_has(a *MfJ, key string) bool {
  var __REGx1 *MfJ= a.field(key); _ = __REGx1
  return __REGx1.kind == int64(3)
}
func Tools_static_sheet(host *McpHost, theme string, a *MfJ, mode string) *Sheet {
  var s *Sheet= CreateNew_Sheet();
  var css string= a.str_("css");
  if  Tools_static_has(a, "css") == false || int64(len(strings.TrimSpace(css))) == int64(0) {
    if  mode == "replace" {
      s.hasCss = true; 
    }
    return s
  }
  if  int64(len(css)) > Deck_static_MAX_CSS() {
    s.err = "css is larger than 100 KB."; 
    return s
  }
  s.hasCss = true; 
  if  mode == "replace" {
    s.css = css; 
    return s
  }
  var base string= host.ThemeCSS(theme);
  if  int64(len(host.Err())) > int64(0) {
    s.fatal = host.Err(); 
    return s
  }
  s.css = ((base + "\n/* --- added for this deck --- */\n") + css) + "\n"; 
  return s
}
func Tools_static_call(host *McpHost, caller *Caller, name string, args *MfJ) *MfJ {
  if  name == "sliqtly_guide" {
    var g *MfJ= MfJ_static_newObj();
    g.put("content", Tools_static_text(host.Asset("guide.md")));
    return g
  }
  if  name == "create_presentation" || name == "update_presentation" {
    var why string= host.RateLimit(caller.who);
    if  int64(len(why)) > int64(0) {
      return Tools_static_fail(why)
    }
  }
  var r *MfJ= CreateNew_MfJ();
  if  name == "create_presentation" {
    r = Tools_static_create(host, caller, args); 
  }
  if  name == "update_presentation" {
    r = Tools_static_update(host, caller, args); 
  }
  if  name == "get_presentation" {
    r = Tools_static_get(host, caller, args); 
  }
  if  name == "list_presentations" {
    r = Tools_static_listMine(host, caller); 
  }
  if  r.kind == int64(0) {
    return r
  }
  var err string= host.Err();
  if  int64(len(err)) > int64(0) && r.bool_("isError", false) == false {
    host.Log((name + " failed: ") + err)
    return Tools_static_fail(((("Sliqtly could not " + Tools_static_verb(name)) + ": ") + err))
  }
  return r
}
func Tools_static_verb(name string) string {
  var u int64= int64(strings.Index(name, "_"));
  if  u < int64(0) {
    return name
  }
  return (name[int64(0):u] + " ") + name[(u + int64(1)):int64(len(name))]
}
func Tools_static_failed(host *McpHost, name string, err string) *MfJ {
  host.Log((name + " failed: ") + err)
  return Tools_static_fail(((("Sliqtly could not " + Tools_static_verb(name)) + ": ") + err))
}
func Tools_static_create(host *McpHost, caller *Caller, a *MfJ) *MfJ {
  var bad string= Tools_static_checkArgs(a, []string {"title", "markdown"});
  if  int64(len(bad)) > int64(0) {
    return Tools_static_fail(bad)
  }
  var md string= a.str_("markdown");
  var theme string= "aurora";
  if  Tools_static_has(a, "theme") {
    theme = a.str_("theme"); 
  }
  var mode string= "extend";
  if  Tools_static_has(a, "css_mode") {
    mode = a.str_("css_mode"); 
  }
  if  int64(len(md)) > Deck_static_MAX_MD() {
    return Tools_static_fail("markdown is larger than 300 KB.")
  }
  if  int64(len(strings.TrimSpace(md))) == int64(0) {
    return Tools_static_fail("markdown is empty.")
  }
  var sh *Sheet= Tools_static_sheet(host, theme, a, mode); _ = sh
  if  int64(len(sh.err)) > int64(0) {
    return Tools_static_fail(sh.err)
  }
  if  int64(len(sh.fatal)) > int64(0) {
    return Tools_static_failed(host, "create_presentation", sh.fatal)
  }
  var loaded *Loaded= Deck_static_loadImages(host, a.list("images")); _ = loaded
  if  int64(len(loaded.err)) > int64(0) {
    return Tools_static_fail(loaded.err)
  }
  var names []string = make([]string, 0);
  for _, im := range loaded.imgs {
    names = append(names,im.name); 
  }
  var none []string = make([]string, 0);
  var o *Outline= Deck_static_outline(md); _ = o
  var ws []string= Deck_static_warnings(md, names, none);
  var out *MfJ= MfJ_static_newObj();
  out.putStr("title", a.str_("title"));
  out.putStr("theme", theme);
  out.putInt("slides", int64(len(o.titles)));
  var base string= host.BaseURL();
  if  host.StoreKind() == "link" {
    if  int64(len(loaded.imgs)) > int64(0) {
      ws = append(ws,"Pictures are not stored on this server (no cloud storage configured); the slides show without them."); 
    }
    out.put("warnings", J_static_strs(ws));
    var q string= "md=" + host.PackText(md);
    q = (q + "&theme=") + host.URIEncode(theme); 
    if  sh.hasCss {
      q = (q + "&css=") + host.PackText(sh.css); 
    }
    out.putStr("share_url", ((base + "/#") + q) + "&mode=show");
    out.putStr("edit_url", (base + "/#") + q);
    return Tools_static_result(caller, out, "Created")
  }
  out.put("warnings", J_static_strs(ws));
  var owner string= "mcp";
  if  caller.signedIn {
    owner = caller.uid; 
  }
  var made *Created= Store_static_create(
    host,
    a.str_("title"),
    md,
    theme,
    sh.hasCss,
    sh.css,
    loaded.imgs,
    owner,
  ); _ = made
  if  int64(len(made.err)) > int64(0) {
    return Tools_static_failed(host, "create_presentation", made.err)
  }
  Tools_static_links(out, base, made.id);
  out.putStr("deck_id", made.id);
  out.putStr("edit_key", made.key);
  return Tools_static_result(caller, out, "Created")
}
func Tools_static_update(host *McpHost, caller *Caller, a *MfJ) *MfJ {
  if  host.StoreKind() == "link" {
    return Tools_static_fail("This server keeps no decks (no cloud storage configured): call create_presentation again with the whole deck.")
  }
  var bad string= Tools_static_checkArgs(a, []string {"deck_id"});
  if  int64(len(bad)) > int64(0) {
    return Tools_static_fail(bad)
  }
  if  Tools_static_has(a, "markdown") && int64(len(a.str_("markdown"))) > Deck_static_MAX_MD() {
    return Tools_static_fail("markdown is larger than 300 KB.")
  }
  var id string= a.str_("deck_id");
  var cur *MfJ= Store_static_get(host, id); _ = cur
  if  int64(len(host.Err())) > int64(0) {
    return Tools_static_failed(host, "update_presentation", host.Err())
  }
  var mine bool= (cur.isObj() && caller.signedIn) && cur.str_("owner") == caller.uid;
  if  cur.isObj() == false || cur.str_("source") != "mcp" && mine == false {
    return Tools_static_fail((("No presentation " + id) + " that this server can change."))
  }
  var key string= a.str_("edit_key");
  if  mine == false && int64(len(key)) == int64(0) {
    return Tools_static_fail("edit_key is needed: the presentation is not this signed-in user's own.")
  }
  var th string= "aurora";
  if  Tools_static_has(a, "theme") {
    th = a.str_("theme"); 
  } else {
    var __REGx1 *MfJ= cur.field("theme"); _ = __REGx1
    if  __REGx1.kind == int64(3) {
      th = cur.str_("theme"); 
    }
  }
  var p *DeckPatch= CreateNew_DeckPatch();
  if  Tools_static_has(a, "css") {
    var mode string= "extend";
    if  Tools_static_has(a, "css_mode") {
      mode = a.str_("css_mode"); 
    }
    var sh *Sheet= Tools_static_sheet(host, th, a, mode); _ = sh
    if  int64(len(sh.err)) > int64(0) {
      return Tools_static_fail(sh.err)
    }
    if  int64(len(sh.fatal)) > int64(0) {
      return Tools_static_failed(host, "update_presentation", sh.fatal)
    }
    if  sh.hasCss {
      p.cssMode = int64(1); 
      p.css = sh.css; 
    } else {
      p.cssMode = int64(2); 
    }
  } else {
    if  Tools_static_has(a, "theme") && a.str_("theme") != cur.str_("theme") {
      p.cssMode = int64(2); 
    }
  }
  if  Tools_static_has(a, "title") {
    p.hasName = true; 
    p.name = a.str_("title"); 
  }
  if  Tools_static_has(a, "markdown") {
    p.hasMd = true; 
    p.md = a.str_("markdown"); 
  }
  if  Tools_static_has(a, "theme") {
    p.hasTheme = true; 
    p.theme = a.str_("theme"); 
  }
  var loaded *Loaded= Deck_static_loadImages(host, a.list("images")); _ = loaded
  if  int64(len(loaded.err)) > int64(0) {
    return Tools_static_fail(loaded.err)
  }
  var saved *MfJ= Store_static_update(host, id, (mine == false), key, p, loaded.imgs); _ = saved
  if  int64(len(host.Err())) > int64(0) {
    return Tools_static_failed(host, "update_presentation", host.Err())
  }
  if  saved.isObj() == false {
    return Tools_static_fail("The edit_key does not match this presentation.")
  }
  var stored []string = make([]string, 0);
  var i int64 = 0;  
  for ; i < int64(len(saved.list("files"))) ; i++ {
    f := saved.list("files")[i]
    var path string= f.str_("path");
    if  strings.HasPrefix(path, "media/") {
      path = path[int64(6):int64(len(path))]; 
    }
    stored = append(stored,path); 
  }
  var md string= saved.str_("md");
  var none []string = make([]string, 0);
  var ws []string = make([]string, 0);
  var j int64 = 0;  
  for ; j < int64(len(Deck_static_warnings(md, none, stored))) ; j++ {
    w := Deck_static_warnings(md, none, stored)[j]
    if  strings.HasPrefix(w, "Image") == false {
      ws = append(ws,w); 
    }
  }
  var o *Outline= Deck_static_outline(md); _ = o
  var out *MfJ= MfJ_static_newObj();
  out.put("title", saved.field("name"));
  out.put("theme", saved.field("theme"));
  out.putInt("slides", int64(len(o.titles)));
  out.put("warnings", J_static_strs(ws));
  Tools_static_links(out, host.BaseURL(), id);
  out.putStr("deck_id", id);
  return Tools_static_result(caller, out, "Updated")
}
func Tools_static_get(host *McpHost, caller *Caller, a *MfJ) *MfJ {
  if  host.StoreKind() == "link" {
    return Tools_static_fail("This server keeps no decks (no cloud storage configured).")
  }
  var bad string= Tools_static_checkArgs(a, []string {"deck_id"});
  if  int64(len(bad)) > int64(0) {
    return Tools_static_fail(bad)
  }
  var id string= a.str_("deck_id");
  if  (int64(len(id)) < int64(6) || int64(len(id)) > int64(32)) || Deck_static_allAlnum(id) == false {
    return Tools_static_fail("deck_id is the 10-character id in the share link.")
  }
  var d *MfJ= Store_static_get(host, id); _ = d
  if  int64(len(host.Err())) > int64(0) {
    return Tools_static_failed(host, "get_presentation", host.Err())
  }
  if  d.isObj() == false {
    return Tools_static_fail((("No presentation " + id) + "."))
  }
  var images *MfJ= MfJ_static_newArr();
  var names []string = make([]string, 0);
  var i int64 = 0;  
  for ; i < int64(len(d.list("files"))) ; i++ {
    f := d.list("files")[i]
    var n string= f.str_("path");
    if  strings.HasPrefix(n, "media/") {
      n = n[int64(6):int64(len(n))]; 
    }
    names = append(names,n); 
    var im *MfJ= MfJ_static_newObj();
    im.putStr("name", n);
    im.put("type", f.field("type"));
    im.put("size", f.field("size"));
    images.add(im);
  }
  var css *MfJ= d.field("css");
  var hasCss bool= css.kind == int64(3);
  var out *MfJ= MfJ_static_newObj();
  out.putStr("title", d.str_("name"));
  out.putStr("theme", d.str_("theme"));
  out.putStr("markdown", d.str_("md"));
  if  hasCss {
    out.put("css", css);
  } else {
    out.put("css", CreateNew_MfJ());
  }
  out.put("images", images);
  Tools_static_links(out, host.BaseURL(), id);
  var themeName string= d.str_("theme");
  if  int64(len(themeName)) == int64(0) {
    themeName = "(document's own)"; 
  }
  var pics string= strings.Join(names, ", ");
  if  int64(len(pics)) == int64(0) {
    pics = "none"; 
  }
  var parts []string = make([]string, 0);
  parts = append(parts,((((((("\"" + out.str_("title")) + "\", theme ") + themeName) + ", ") + strconv.FormatInt(int64(len(names)), 10)) + " pictures: ") + pics) + "."); 
  if  hasCss {
    parts = append(parts,"It has its own stylesheet (css below)."); 
  }
  parts = append(parts,"```markdown"); 
  var md string= d.str_("md");
  if  int64(len(md)) > int64(0) {
    parts = append(parts,md); 
  }
  parts = append(parts,"```"); 
  if  hasCss {
    parts = append(parts,("```css\n" + css.str) + "\n```"); 
  }
  var r *MfJ= MfJ_static_newObj();
  r.put("content", Tools_static_text(strings.Join(parts, "\n")));
  r.put("structuredContent", out);
  return r
}
func Tools_static_listMine(host *McpHost, caller *Caller) *MfJ {
  if  caller.signedIn == false {
    var r *MfJ= Tools_static_fail("Listing presentations needs sign-in. Connect Sliqtly with sign-in (Google) to keep presentations in your own account.");
    if  int64(len(caller.signIn)) > int64(0) {
      var meta *MfJ= MfJ_static_newObj();
      meta.put("mcp/www_authenticate", J_static_strs([]string {(("Bearer resource_metadata=\"" + caller.signIn) + "\", error=\"insufficient_scope\", error_description=\"Sign in to Sliqtly to list your presentations\"")}));
      r.put("_meta", meta);
    }
    return r
  }
  if  host.StoreKind() == "link" {
    return Tools_static_fail("This server keeps no decks (no cloud storage configured).")
  }
  var docs []*MfJ= Store_static_list(host, caller.uid);
  if  int64(len(host.Err())) > int64(0) {
    return Tools_static_failed(host, "list_presentations", host.Err())
  }
  var base string= host.BaseURL();
  var decks *MfJ= MfJ_static_newArr();
  var lines []string = make([]string, 0);
  for _, d := range docs {
    var id string= d.str_("id");
    var deck *MfJ= MfJ_static_newObj();
    deck.putStr("deck_id", id);
    deck.putStr("title", d.str_("name"));
    deck.putStr("theme", d.str_("theme"));
    var t float64= Store_static_stamp(d);
    if  t > 0.0 {
      deck.putStr("updated", host.ISOTime(int64(math.Floor(t))));
    } else {
      deck.put("updated", CreateNew_MfJ());
    }
    Tools_static_links(deck, base, id);
    decks.add(deck);
    var title string= d.str_("name");
    if  int64(len(title)) == int64(0) {
      title = "(untitled)"; 
    }
    lines = append(lines,(((("- " + title) + " (") + id) + "): ") + deck.str_("share_url")); 
  }
  var txt string= strings.Join(lines, "\n");
  if  int64(len(lines)) == int64(0) {
    txt = "No presentations yet."; 
  }
  var sc *MfJ= MfJ_static_newObj();
  sc.put("presentations", decks);
  var r2 *MfJ= MfJ_static_newObj();
  r2.put("content", Tools_static_text(txt));
  r2.put("structuredContent", sc);
  return r2
}
type Sheet struct { 
  hasCss bool `json:"hasCss"` 
  css string `json:"css"` 
  err string `json:"err"` 
  fatal string `json:"fatal"` 
}

func CreateNew_Sheet() *Sheet {
  me := new(Sheet)
  me.hasCss = false
  me.css = ""
  me.err = ""
  me.fatal = ""
  return me;
}
type Mcp struct { 
}

func CreateNew_Mcp() *Mcp {
  me := new(Mcp)
  return me;
}
func Mcp_static_VERSIONS() []string {
  return []string {"2025-11-25", "2025-06-18", "2025-03-26", "2024-11-05", "2024-10-07"}
}
func Mcp_static_SERVER_VERSION() string {
  return "1.0.0"
}
func Mcp_static_error(id *MfJ, code int64, message string) *MfJ {
  var e *MfJ= MfJ_static_newObj();
  e.putInt("code", code);
  e.putStr("message", message);
  var r *MfJ= MfJ_static_newObj();
  r.putStr("jsonrpc", "2.0");
  r.put("id", id);
  r.put("error", e);
  return r
}
func Mcp_static_ok(id *MfJ, result *MfJ) *MfJ {
  var r *MfJ= MfJ_static_newObj();
  r.putStr("jsonrpc", "2.0");
  r.put("id", id);
  r.put("result", result);
  return r
}
func Mcp_static_initialize(host *McpHost, params *MfJ) *MfJ {
  var asked string= params.str_("protocolVersion");
  var version string= Mcp_static_VERSIONS()[int64(0)];
  if  Deck_static_inList(Mcp_static_VERSIONS(), asked) {
    version = asked; 
  }
  var caps *MfJ= MfJ_static_newObj();
  var tools *MfJ= MfJ_static_newObj();
  tools.putBool("listChanged", true);
  caps.put("tools", tools);
  var res *MfJ= MfJ_static_newObj();
  res.putBool("listChanged", true);
  caps.put("resources", res);
  var info *MfJ= MfJ_static_newObj();
  info.putStr("name", "sliqtly");
  info.putStr("title", "Sliqtly");
  info.putStr("version", Mcp_static_SERVER_VERSION());
  info.putStr("websiteUrl", host.BaseURL());
  var out *MfJ= MfJ_static_newObj();
  out.putStr("protocolVersion", version);
  out.put("capabilities", caps);
  out.put("serverInfo", info);
  out.putStr("instructions", "Sliqtly turns Markdown into animated slide presentations. Call sliqtly_guide once for the syntax, then create_presentation. Always give the user the returned presentation link.");
  return out
}
func Mcp_static_handle(host *McpHost, caller *Caller, msg *MfJ) *MfJ {
  if  msg.isObj() == false {
    return Mcp_static_error(CreateNew_MfJ(), int64(-32600), "Invalid Request")
  }
  var method string= msg.str_("method");
  var hasId bool= msg.has("id");
  var id *MfJ= msg.field("id");
  if  int64(len(method)) == int64(0) {
    if  msg.has("result") || msg.has("error") {
      return CreateNew_MfJ()
    }
    return Mcp_static_error(id, int64(-32600), "Invalid Request")
  }
  if  hasId == false {
    return CreateNew_MfJ()
  }
  var params *MfJ= msg.field("params");
  if  method == "initialize" {
    return Mcp_static_ok(id, Mcp_static_initialize(host, params))
  }
  if  method == "ping" {
    return Mcp_static_ok(id, MfJ_static_newObj())
  }
  if  method == "tools/list" {
    var tl *MfJ= MfJ_static_newObj();
    tl.put("tools", Tools_static_list());
    return Mcp_static_ok(id, tl)
  }
  if  method == "tools/call" {
    var name string= params.str_("name");
    var r *MfJ= Tools_static_call(host, caller, name, params.field("arguments"));
    if  r.kind == int64(0) {
      return Mcp_static_error(
        id,
        int64(-32602),
        (("MCP error -32602: Tool " + name) + " not found"),
      )
    }
    return Mcp_static_ok(id, r)
  }
  if  method == "resources/list" {
    var rl *MfJ= MfJ_static_newObj();
    rl.put("resources", Tools_static_resources(host.BaseURL()));
    return Mcp_static_ok(id, rl)
  }
  if  method == "resources/templates/list" {
    var tl2 *MfJ= MfJ_static_newObj();
    tl2.put("resourceTemplates", MfJ_static_newArr());
    return Mcp_static_ok(id, tl2)
  }
  if  method == "resources/read" {
    var uri string= params.str_("uri");
    var rr *MfJ= Tools_static_read(host, uri);
    if  rr.kind == int64(0) {
      return Mcp_static_error(id, int64(-32002), (("Resource " + uri) + " not found"))
    }
    return Mcp_static_ok(id, rr)
  }
  return Mcp_static_error(id, int64(-32601), "Method not found")
}
func Mcp_static_post(host *McpHost, caller *Caller, body string) *McpReply {
  var reply *McpReply= CreateNew_McpReply();
  if  int64(len(body)) == int64(0) {
    reply.status = int64(400); 
    reply.body = JOut_static_text(Mcp_static_error(
      CreateNew_MfJ(),
      int64(-32700),
      "Parse error: Invalid JSON",
    )); 
    return reply
  }
  var msg *MfJ= MfJ_static_parse(body);
  if  msg.isArr() {
    var answers *MfJ= MfJ_static_newArr();
    for _, m := range msg.arr {
      var a *MfJ= Mcp_static_handle(host, caller, m);
      if  a.kind != int64(0) {
        answers.add(a);
      }
    }
    if  answers.count() == int64(0) {
      reply.status = int64(202); 
      return reply
    }
    reply.body = JOut_static_text(answers); 
    return reply
  }
  var one *MfJ= Mcp_static_handle(host, caller, msg);
  if  one.kind == int64(0) {
    reply.status = int64(202); 
    return reply
  }
  reply.body = JOut_static_text(one); 
  return reply
}
type McpReply struct { 
  status int64 `json:"status"` 
  body string `json:"body"` 
}

func CreateNew_McpReply() *McpReply {
  me := new(McpReply)
  me.status = int64(200)
  me.body = ""
  return me;
}
type App struct { 
}

func CreateNew_App() *App {
  me := new(App)
  return me;
}
func App_static_cors(res http.ResponseWriter) () {
  res.Header().Set("Access-Control-Allow-Origin", "*")
  res.Header().Set("Access-Control-Allow-Headers", "content-type, mcp-session-id, mcp-protocol-version, authorization, last-event-id")
  res.Header().Set("Access-Control-Expose-Headers", "mcp-session-id, mcp-protocol-version, www-authenticate")
  res.Header().Set("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
}
func App_static_sendJson(res http.ResponseWriter, status int64, body string) () {
  res.Header().Set("Content-Type", "application/json; charset=utf-8")
  res.WriteHeader(int(status))
  res.Write([]byte(body))
}
func App_static_redirect(res http.ResponseWriter, url string) () {
  res.Header().Set("Location", url)
  res.WriteHeader(int(int64(302)))
}
func App_static_send(res http.ResponseWriter, out *HttpOut) () {
  if  int64(len(out.redirect)) > int64(0) {
    App_static_redirect(res, out.redirect);
    return
  }
  if  int64(len(out.text)) > int64(0) {
    res.Header().Set("Content-Type", "text/plain; charset=utf-8")
    res.WriteHeader(int(out.status))
    res.Write([]byte(out.text))
    return
  }
  if  out.noStore {
    res.Header().Set("Cache-Control", "no-store")
  }
  App_static_sendJson(res, out.status, JOut_static_text(out.json));
}
func App_static_originOf(host *McpHost, req *http.Request) string {
  var base string= host.BaseURL();
  var h string= req.Header.Get("X-Forwarded-Host");
  if  int64(len(h)) == int64(0) {
    h = req.Header.Get("Host"); 
  }
  if  int64(len(h)) == int64(0) {
    h = req.Host; 
  }
  var comma int64= int64(strings.Index(h, ","));
  if  comma >= int64(0) {
    h = h[int64(0):comma]; 
  }
  h = strings.TrimSpace(h); 
  var https string= "https://" + h;
  if  (https == "https://sliqtly.com" || https == "https://sliqtly.web.app") || https == base {
    return https
  }
  if  host.TrustHost() && int64(len(h)) > int64(0) {
    if  host.TLS() {
      return "https://" + h
    }
    return "http://" + h
  }
  return base
}
func App_static_rpcError(code int64, message string) string {
  return JOut_static_text(Mcp_static_error(CreateNew_MfJ(), code, message))
}
func App_static_serve(host *McpHost, req *http.Request, res http.ResponseWriter) () {
  App_static_cors(res);
  var method string= req.Method;
  var path string= req.URL.Path;
  if  method == "OPTIONS" {
    res.WriteHeader(int(int64(204)))
    return
  }
  if  host.OAuthOn() {
    if  App_static_serveOAuth(host, req, res, method, path) {
      return
    }
  }
  if  path == "/mcp" {
    App_static_serveMcp(host, req, res, method);
    return
  }
  res.Header().Set("Content-Type", "text/plain; charset=utf-8")
  res.WriteHeader(int(int64(404)))
  res.Write([]byte((("Cannot " + method) + " ") + path))
}
func App_static_serveOAuth(host *McpHost, req *http.Request, res http.ResponseWriter, method string, path string) bool {
  if  method == "GET" {
    if  path == "/.well-known/oauth-protected-resource" || path == "/.well-known/oauth-protected-resource/mcp" {
      App_static_sendJson(
        res,
        int64(200),
        JOut_static_text(OAuth_static_resourceMetadata(App_static_originOf(host, req))),
      );
      return true
    }
    if  path == "/.well-known/oauth-authorization-server" || path == "/.well-known/openid-configuration" {
      App_static_sendJson(
        res,
        int64(200),
        JOut_static_text(OAuth_static_metadata(App_static_originOf(host, req))),
      );
      return true
    }
    if  path == "/oauth/authorize" {
      var q *MfJ= J_static_parse(queryJSON(req));
      App_static_send(res, OAuth_static_authorize(host, q, App_static_originOf(host, req)));
      return true
    }
    return false
  }
  if  method != "POST" {
    return false
  }
  if  (path != "/oauth/register" && path != "/oauth/approve") && path != "/oauth/token" {
    return false
  }
  var body *MfJ= J_static_parse(host.BodyJSON());
  if  body.isObj() == false {
    body = MfJ_static_newObj(); 
  }
  if  path == "/oauth/register" {
    App_static_send(res, OAuth_static_register(host, body));
  }
  if  path == "/oauth/approve" {
    App_static_send(res, OAuth_static_approve(host, body));
  }
  if  path == "/oauth/token" {
    App_static_send(res, OAuth_static_token(host, body));
  }
  return true
}
func App_static_serveMcp(host *McpHost, req *http.Request, res http.ResponseWriter, method string) () {
  var accept string= req.Header.Get("Accept");
  if  method == "GET" && int64(strings.Index(accept, "text/event-stream")) < int64(0) {
    App_static_redirect(res, host.BaseURL() + "/connect.html");
    return
  }
  if  method != "POST" {
    res.Header().Set("Allow", "POST")
    App_static_sendJson(
      res,
      int64(405),
      App_static_rpcError(int64(-32000), "Method not allowed: this server is stateless, POST only."),
    );
    return
  }
  var caller *Caller= CreateNew_Caller();
  if  host.OAuthOn() {
    var origin string= App_static_originOf(host, req);
    var w *Who= OAuth_static_who(host, req.Header.Get("Authorization")); _ = w
    if  w.state == int64(3) {
      host.Log("token check failed: " + host.Err())
      App_static_sendJson(res, int64(500), App_static_rpcError(int64(-32603), "Internal error"));
      return
    }
    if  w.state == int64(2) {
      res.Header().Set("WWW-Authenticate", ("Bearer error=\"invalid_token\", resource_metadata=\"" + origin) + "/.well-known/oauth-protected-resource/mcp\"")
      App_static_sendJson(
        res,
        int64(401),
        App_static_rpcError(int64(-32001), "The sign-in has expired."),
      );
      return
    }
    if  w.state == int64(1) {
      caller.signedIn = true; 
      caller.uid = w.uid; 
      caller.name = w.name; 
    }
    caller.signIn = origin + "/.well-known/oauth-protected-resource/mcp"; 
  }
  var ip string= req.Header.Get("X-Forwarded-For");
  var comma int64= int64(strings.Index(ip, ","));
  if  comma >= int64(0) {
    ip = ip[int64(0):comma]; 
  }
  ip = strings.TrimSpace(ip); 
  if  int64(len(ip)) == int64(0) {
    ip = host.RemoteIP(); 
  }
  caller.who = ip; 
  if  caller.signedIn {
    caller.who = "uid:" + caller.uid; 
  }
  if  int64(strings.Index(accept, "application/json")) < int64(0) || int64(strings.Index(accept, "text/event-stream")) < int64(0) {
    App_static_sendJson(
      res,
      int64(406),
      App_static_rpcError(int64(-32000), "Not Acceptable: Client must accept both application/json and text/event-stream"),
    );
    return
  }
  if  int64(strings.Index(strings.ToLower(req.Header.Get("Content-Type")), "application/json")) < int64(0) {
    App_static_sendJson(
      res,
      int64(415),
      App_static_rpcError(int64(-32000), "Unsupported Media Type: Content-Type must be application/json"),
    );
    return
  }
  var pv string= req.Header.Get("Mcp-Protocol-Version");
  if  int64(len(pv)) > int64(0) && Deck_static_inList(Mcp_static_VERSIONS(), pv) == false {
    App_static_sendJson(
      res,
      int64(400),
      App_static_rpcError(int64(-32000), ("Bad Request: Unsupported protocol version: " + pv)),
    );
    return
  }
  var reply *McpReply= Mcp_static_post(host, caller, host.BodyJSON()); _ = reply
  if  reply.status == int64(202) {
    res.WriteHeader(int(int64(202)))
    return
  }
  App_static_sendJson(res, reply.status, reply.body);
}
